/**
 * Cloud Storage Integration Nodes
 *
 * AWS S3, Dropbox, Google Drive, OneDrive, Box, FTP, etc.
 */

import type { NodeSchema } from "../types.js";

export const CLOUD_STORAGE_NODES: Record<string, NodeSchema> = {
  "n8n-nodes-base.awsS3": {
    type: "n8n-nodes-base.awsS3",
    displayName: "AWS S3",
    description: "Upload, download, and manage files in Amazon S3",
    category: "storage",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "aws", required: true, description: "AWS credentials with S3 access" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "file",
        description: "Resource to operate on",
        options: [
          { name: "Bucket", value: "bucket", description: "Manage buckets" },
          { name: "File", value: "file", description: "Manage files" },
          { name: "Folder", value: "folder", description: "Manage folders" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "upload",
        description: "Operation to perform",
        options: [
          { name: "Copy", value: "copy", description: "Copy a file" },
          { name: "Delete", value: "delete", description: "Delete a file" },
          { name: "Download", value: "download", description: "Download a file" },
          { name: "Get All", value: "getAll", description: "List all files" },
          { name: "Upload", value: "upload", description: "Upload a file" },
        ],
        displayOptions: { show: { resource: ["file"] } },
      },
      {
        name: "bucketName",
        type: "string",
        required: true,
        default: "",
        description: "S3 bucket name",
      },
      {
        name: "fileName",
        type: "string",
        required: true,
        default: "",
        description: "File name/key in S3",
        displayOptions: { show: { resource: ["file"], operation: ["upload", "download", "delete", "copy"] } },
      },
      {
        name: "binaryPropertyName",
        type: "string",
        required: true,
        default: "data",
        description: "Binary property name for file data",
        displayOptions: { show: { resource: ["file"], operation: ["upload", "download"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields",
      },
    ],
    examples: [
      {
        name: "Upload File",
        description: "Upload a file to S3",
        parameters: {
          resource: "file",
          operation: "upload",
          bucketName: "my-bucket",
          fileName: "uploads/file.pdf",
          binaryPropertyName: "data",
        },
      },
      {
        name: "Download File",
        description: "Download a file from S3",
        parameters: {
          resource: "file",
          operation: "download",
          bucketName: "my-bucket",
          fileName: "documents/report.pdf",
          binaryPropertyName: "data",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.awss3/",
  },

  "n8n-nodes-base.dropbox": {
    type: "n8n-nodes-base.dropbox",
    displayName: "Dropbox",
    description: "Upload, download, and manage files in Dropbox",
    category: "storage",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "dropboxApi", required: false, description: "Dropbox API credentials" },
      { name: "dropboxOAuth2Api", required: false, description: "Dropbox OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "file",
        description: "Resource to operate on",
        options: [
          { name: "File", value: "file", description: "Manage files" },
          { name: "Folder", value: "folder", description: "Manage folders" },
          { name: "Search", value: "search", description: "Search files" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "upload",
        description: "Operation to perform",
        options: [
          { name: "Copy", value: "copy", description: "Copy a file" },
          { name: "Delete", value: "delete", description: "Delete a file" },
          { name: "Download", value: "download", description: "Download a file" },
          { name: "Move", value: "move", description: "Move a file" },
          { name: "Upload", value: "upload", description: "Upload a file" },
        ],
        displayOptions: { show: { resource: ["file"] } },
      },
      {
        name: "path",
        type: "string",
        required: true,
        default: "",
        description: "File or folder path",
        placeholder: "/Documents/file.pdf",
      },
      {
        name: "binaryPropertyName",
        type: "string",
        required: true,
        default: "data",
        description: "Binary property name",
        displayOptions: { show: { resource: ["file"], operation: ["upload", "download"] } },
      },
    ],
    examples: [
      {
        name: "Upload File",
        description: "Upload a file to Dropbox",
        parameters: {
          resource: "file",
          operation: "upload",
          path: "/uploads/document.pdf",
          binaryPropertyName: "data",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.dropbox/",
  },

  "n8n-nodes-base.googleDrive": {
    type: "n8n-nodes-base.googleDrive",
    displayName: "Google Drive",
    description: "Upload, download, and manage files in Google Drive",
    category: "storage",
    typeVersion: 3,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "googleDriveOAuth2Api", required: true, description: "Google OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "file",
        description: "Resource to operate on",
        options: [
          { name: "Drive", value: "drive", description: "Manage shared drives" },
          { name: "File", value: "file", description: "Manage files" },
          { name: "Folder", value: "folder", description: "Manage folders" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "upload",
        description: "Operation to perform",
        options: [
          { name: "Copy", value: "copy", description: "Copy a file" },
          { name: "Delete", value: "delete", description: "Delete a file" },
          { name: "Download", value: "download", description: "Download a file" },
          { name: "List", value: "list", description: "List files" },
          { name: "Move", value: "move", description: "Move a file" },
          { name: "Share", value: "share", description: "Share a file" },
          { name: "Update", value: "update", description: "Update a file" },
          { name: "Upload", value: "upload", description: "Upload a file" },
        ],
        displayOptions: { show: { resource: ["file"] } },
      },
      {
        name: "fileId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "File ID",
        displayOptions: { show: { resource: ["file"], operation: ["download", "delete", "copy", "move", "share", "update"] } },
      },
      {
        name: "folderId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Folder ID to upload to",
        displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
      },
      {
        name: "name",
        type: "string",
        required: true,
        default: "",
        description: "File name",
        displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
      },
      {
        name: "binaryPropertyName",
        type: "string",
        required: true,
        default: "data",
        description: "Binary property name",
        displayOptions: { show: { resource: ["file"], operation: ["upload", "download"] } },
      },
      {
        name: "options",
        type: "collection",
        required: false,
        default: {},
        description: "Additional options",
      },
    ],
    examples: [
      {
        name: "Upload File",
        description: "Upload a file to Google Drive",
        parameters: {
          resource: "file",
          operation: "upload",
          folderId: "folder-id",
          name: "document.pdf",
          binaryPropertyName: "data",
        },
      },
      {
        name: "List Files",
        description: "List files in a folder",
        parameters: {
          resource: "file",
          operation: "list",
          options: { folderId: "folder-id" },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.googledrive/",
  },

  "n8n-nodes-base.microsoftOneDrive": {
    type: "n8n-nodes-base.microsoftOneDrive",
    displayName: "Microsoft OneDrive",
    description: "Upload, download, and manage files in OneDrive",
    category: "storage",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "microsoftOneDriveOAuth2Api", required: true, description: "Microsoft OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "file",
        description: "Resource to operate on",
        options: [
          { name: "File", value: "file", description: "Manage files" },
          { name: "Folder", value: "folder", description: "Manage folders" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "upload",
        description: "Operation to perform",
        options: [
          { name: "Copy", value: "copy", description: "Copy a file" },
          { name: "Delete", value: "delete", description: "Delete a file" },
          { name: "Download", value: "download", description: "Download a file" },
          { name: "Get Link", value: "getLink", description: "Get share link" },
          { name: "List", value: "list", description: "List files" },
          { name: "Move", value: "move", description: "Move a file" },
          { name: "Upload", value: "upload", description: "Upload a file" },
        ],
        displayOptions: { show: { resource: ["file"] } },
      },
      {
        name: "fileId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "File ID",
        displayOptions: { show: { resource: ["file"], operation: ["download", "delete", "copy", "move", "getLink"] } },
      },
      {
        name: "fileName",
        type: "string",
        required: true,
        default: "",
        description: "File name",
        displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
      },
      {
        name: "binaryPropertyName",
        type: "string",
        required: true,
        default: "data",
        description: "Binary property name",
        displayOptions: { show: { resource: ["file"], operation: ["upload", "download"] } },
      },
    ],
    examples: [
      {
        name: "Upload File",
        description: "Upload a file to OneDrive",
        parameters: {
          resource: "file",
          operation: "upload",
          fileName: "document.pdf",
          binaryPropertyName: "data",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.microsoftonedrive/",
  },

  "n8n-nodes-base.box": {
    type: "n8n-nodes-base.box",
    displayName: "Box",
    description: "Upload, download, and manage files in Box",
    category: "storage",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "boxOAuth2Api", required: true, description: "Box OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "file",
        description: "Resource to operate on",
        options: [
          { name: "File", value: "file", description: "Manage files" },
          { name: "Folder", value: "folder", description: "Manage folders" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "upload",
        description: "Operation to perform",
        options: [
          { name: "Copy", value: "copy", description: "Copy a file" },
          { name: "Delete", value: "delete", description: "Delete a file" },
          { name: "Download", value: "download", description: "Download a file" },
          { name: "Get", value: "get", description: "Get file info" },
          { name: "Search", value: "search", description: "Search files" },
          { name: "Share", value: "share", description: "Share a file" },
          { name: "Upload", value: "upload", description: "Upload a file" },
        ],
        displayOptions: { show: { resource: ["file"] } },
      },
      {
        name: "fileId",
        type: "string",
        required: true,
        default: "",
        description: "File ID",
        displayOptions: { show: { resource: ["file"], operation: ["download", "delete", "copy", "get", "share"] } },
      },
      {
        name: "parentId",
        type: "string",
        required: true,
        default: "0",
        description: "Parent folder ID (0 for root)",
        displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
      },
      {
        name: "fileName",
        type: "string",
        required: true,
        default: "",
        description: "File name",
        displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
      },
      {
        name: "binaryPropertyName",
        type: "string",
        required: true,
        default: "data",
        description: "Binary property name",
        displayOptions: { show: { resource: ["file"], operation: ["upload", "download"] } },
      },
    ],
    examples: [
      {
        name: "Upload File",
        description: "Upload a file to Box",
        parameters: {
          resource: "file",
          operation: "upload",
          parentId: "0",
          fileName: "document.pdf",
          binaryPropertyName: "data",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.box/",
  },

  "n8n-nodes-base.ftp": {
    type: "n8n-nodes-base.ftp",
    displayName: "FTP",
    description: "Upload, download, and manage files via FTP",
    category: "storage",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "ftp", required: true, description: "FTP server credentials" },
    ],
    parameters: [
      {
        name: "operation",
        type: "options",
        required: true,
        default: "list",
        description: "Operation to perform",
        options: [
          { name: "Delete", value: "delete", description: "Delete a file" },
          { name: "Download", value: "download", description: "Download a file" },
          { name: "List", value: "list", description: "List files" },
          { name: "Rename", value: "rename", description: "Rename a file" },
          { name: "Upload", value: "upload", description: "Upload a file" },
        ],
      },
      {
        name: "path",
        type: "string",
        required: true,
        default: "/",
        description: "Remote path",
      },
      {
        name: "binaryPropertyName",
        type: "string",
        required: true,
        default: "data",
        description: "Binary property name",
        displayOptions: { show: { operation: ["upload", "download"] } },
      },
      {
        name: "options",
        type: "collection",
        required: false,
        default: {},
        description: "Additional options",
      },
    ],
    examples: [
      {
        name: "List Files",
        description: "List files in a directory",
        parameters: {
          operation: "list",
          path: "/uploads",
        },
      },
      {
        name: "Upload File",
        description: "Upload a file via FTP",
        parameters: {
          operation: "upload",
          path: "/uploads/file.txt",
          binaryPropertyName: "data",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.ftp/",
  },

  "n8n-nodes-base.ssh": {
    type: "n8n-nodes-base.ssh",
    displayName: "SSH",
    description: "Execute commands and transfer files via SSH",
    category: "storage",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "sshPassword", required: false, description: "SSH password credentials" },
      { name: "sshPrivateKey", required: false, description: "SSH private key credentials" },
    ],
    parameters: [
      {
        name: "operation",
        type: "options",
        required: true,
        default: "execute",
        description: "Operation to perform",
        options: [
          { name: "Download", value: "download", description: "Download a file" },
          { name: "Execute", value: "execute", description: "Execute a command" },
          { name: "Upload", value: "upload", description: "Upload a file" },
        ],
      },
      {
        name: "command",
        type: "string",
        required: true,
        default: "",
        description: "Command to execute",
        displayOptions: { show: { operation: ["execute"] } },
      },
      {
        name: "path",
        type: "string",
        required: true,
        default: "",
        description: "Remote file path",
        displayOptions: { show: { operation: ["upload", "download"] } },
      },
      {
        name: "binaryPropertyName",
        type: "string",
        required: true,
        default: "data",
        description: "Binary property name",
        displayOptions: { show: { operation: ["upload", "download"] } },
      },
    ],
    examples: [
      {
        name: "Execute Command",
        description: "Run a command via SSH",
        parameters: {
          operation: "execute",
          command: "ls -la /var/log",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.ssh/",
  },

  "n8n-nodes-base.sftp": {
    type: "n8n-nodes-base.sftp",
    displayName: "SFTP",
    description: "Upload, download, and manage files via SFTP",
    category: "storage",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "sftp", required: true, description: "SFTP credentials" },
    ],
    parameters: [
      {
        name: "operation",
        type: "options",
        required: true,
        default: "list",
        description: "Operation to perform",
        options: [
          { name: "Delete", value: "delete", description: "Delete a file" },
          { name: "Download", value: "download", description: "Download a file" },
          { name: "List", value: "list", description: "List files" },
          { name: "Rename", value: "rename", description: "Rename a file" },
          { name: "Upload", value: "upload", description: "Upload a file" },
        ],
      },
      {
        name: "path",
        type: "string",
        required: true,
        default: "/",
        description: "Remote path",
      },
      {
        name: "binaryPropertyName",
        type: "string",
        required: true,
        default: "data",
        description: "Binary property name",
        displayOptions: { show: { operation: ["upload", "download"] } },
      },
    ],
    examples: [
      {
        name: "Upload File",
        description: "Upload a file via SFTP",
        parameters: {
          operation: "upload",
          path: "/uploads/file.txt",
          binaryPropertyName: "data",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.sftp/",
  },

  "n8n-nodes-base.nextCloud": {
    type: "n8n-nodes-base.nextCloud",
    displayName: "Nextcloud",
    description: "Upload, download, and manage files in Nextcloud",
    category: "storage",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "nextCloudApi", required: true, description: "Nextcloud API credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "file",
        description: "Resource to operate on",
        options: [
          { name: "File", value: "file", description: "Manage files" },
          { name: "Folder", value: "folder", description: "Manage folders" },
          { name: "User", value: "user", description: "Manage users" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "upload",
        description: "Operation to perform",
        options: [
          { name: "Copy", value: "copy", description: "Copy a file" },
          { name: "Delete", value: "delete", description: "Delete a file" },
          { name: "Download", value: "download", description: "Download a file" },
          { name: "List", value: "list", description: "List files" },
          { name: "Move", value: "move", description: "Move a file" },
          { name: "Share", value: "share", description: "Share a file" },
          { name: "Upload", value: "upload", description: "Upload a file" },
        ],
        displayOptions: { show: { resource: ["file"] } },
      },
      {
        name: "path",
        type: "string",
        required: true,
        default: "",
        description: "File or folder path",
      },
      {
        name: "binaryPropertyName",
        type: "string",
        required: true,
        default: "data",
        description: "Binary property name",
        displayOptions: { show: { resource: ["file"], operation: ["upload", "download"] } },
      },
    ],
    examples: [
      {
        name: "Upload File",
        description: "Upload a file to Nextcloud",
        parameters: {
          resource: "file",
          operation: "upload",
          path: "/Documents/file.pdf",
          binaryPropertyName: "data",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.nextcloud/",
  },

  "n8n-nodes-base.webdav": {
    type: "n8n-nodes-base.webdav",
    displayName: "WebDAV",
    description: "Upload, download, and manage files via WebDAV",
    category: "storage",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "webDav", required: true, description: "WebDAV credentials" },
    ],
    parameters: [
      {
        name: "operation",
        type: "options",
        required: true,
        default: "list",
        description: "Operation to perform",
        options: [
          { name: "Copy", value: "copy", description: "Copy a file" },
          { name: "Delete", value: "delete", description: "Delete a file" },
          { name: "Download", value: "download", description: "Download a file" },
          { name: "List", value: "list", description: "List files" },
          { name: "Move", value: "move", description: "Move a file" },
          { name: "Upload", value: "upload", description: "Upload a file" },
        ],
      },
      {
        name: "path",
        type: "string",
        required: true,
        default: "/",
        description: "File or folder path",
      },
      {
        name: "binaryPropertyName",
        type: "string",
        required: true,
        default: "data",
        description: "Binary property name",
        displayOptions: { show: { operation: ["upload", "download"] } },
      },
    ],
    examples: [
      {
        name: "List Files",
        description: "List files in a directory",
        parameters: {
          operation: "list",
          path: "/documents",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.webdav/",
  },

  "n8n-nodes-base.minIo": {
    type: "n8n-nodes-base.minIo",
    displayName: "MinIO",
    description: "Upload, download, and manage files in MinIO",
    category: "storage",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "minIo", required: true, description: "MinIO credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "file",
        description: "Resource to operate on",
        options: [
          { name: "Bucket", value: "bucket", description: "Manage buckets" },
          { name: "File", value: "file", description: "Manage files" },
          { name: "Folder", value: "folder", description: "Manage folders" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "upload",
        description: "Operation to perform",
        options: [
          { name: "Copy", value: "copy", description: "Copy a file" },
          { name: "Delete", value: "delete", description: "Delete a file" },
          { name: "Download", value: "download", description: "Download a file" },
          { name: "Get All", value: "getAll", description: "List files" },
          { name: "Upload", value: "upload", description: "Upload a file" },
        ],
        displayOptions: { show: { resource: ["file"] } },
      },
      {
        name: "bucketName",
        type: "string",
        required: true,
        default: "",
        description: "Bucket name",
      },
      {
        name: "fileName",
        type: "string",
        required: true,
        default: "",
        description: "File name/key",
        displayOptions: { show: { resource: ["file"], operation: ["upload", "download", "delete", "copy"] } },
      },
      {
        name: "binaryPropertyName",
        type: "string",
        required: true,
        default: "data",
        description: "Binary property name",
        displayOptions: { show: { resource: ["file"], operation: ["upload", "download"] } },
      },
    ],
    examples: [
      {
        name: "Upload File",
        description: "Upload a file to MinIO",
        parameters: {
          resource: "file",
          operation: "upload",
          bucketName: "my-bucket",
          fileName: "uploads/file.pdf",
          binaryPropertyName: "data",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.minio/",
  },

  "n8n-nodes-base.googleCloudStorage": {
    type: "n8n-nodes-base.googleCloudStorage",
    displayName: "Google Cloud Storage",
    description: "Upload, download, and manage files in GCS",
    category: "storage",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "googleCloudStorageOAuth2Api", required: true, description: "Google OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "object",
        description: "Resource to operate on",
        options: [
          { name: "Bucket", value: "bucket", description: "Manage buckets" },
          { name: "Object", value: "object", description: "Manage objects" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "upload",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Upload an object" },
          { name: "Delete", value: "delete", description: "Delete an object" },
          { name: "Get", value: "get", description: "Download an object" },
          { name: "Get All", value: "getAll", description: "List objects" },
        ],
        displayOptions: { show: { resource: ["object"] } },
      },
      {
        name: "bucketName",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Bucket name",
      },
      {
        name: "objectName",
        type: "string",
        required: true,
        default: "",
        description: "Object name/key",
        displayOptions: { show: { resource: ["object"], operation: ["create", "get", "delete"] } },
      },
      {
        name: "binaryPropertyName",
        type: "string",
        required: true,
        default: "data",
        description: "Binary property name",
        displayOptions: { show: { resource: ["object"], operation: ["create", "get"] } },
      },
    ],
    examples: [
      {
        name: "Upload Object",
        description: "Upload a file to GCS",
        parameters: {
          resource: "object",
          operation: "create",
          bucketName: "my-bucket",
          objectName: "uploads/file.pdf",
          binaryPropertyName: "data",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.googlecloudstorage/",
  },

  "n8n-nodes-base.backblaze": {
    type: "n8n-nodes-base.backblaze",
    displayName: "Backblaze B2",
    description: "Upload, download, and manage files in Backblaze B2",
    category: "storage",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "backblazeApi", required: true, description: "Backblaze B2 credentials" },
    ],
    parameters: [
      {
        name: "operation",
        type: "options",
        required: true,
        default: "upload",
        description: "Operation to perform",
        options: [
          { name: "Delete", value: "delete", description: "Delete a file" },
          { name: "Download", value: "download", description: "Download a file" },
          { name: "Get All", value: "getAll", description: "List files" },
          { name: "Upload", value: "upload", description: "Upload a file" },
        ],
      },
      {
        name: "bucketId",
        type: "string",
        required: true,
        default: "",
        description: "Bucket ID",
      },
      {
        name: "fileName",
        type: "string",
        required: true,
        default: "",
        description: "File name",
        displayOptions: { show: { operation: ["upload", "download", "delete"] } },
      },
      {
        name: "binaryPropertyName",
        type: "string",
        required: true,
        default: "data",
        description: "Binary property name",
        displayOptions: { show: { operation: ["upload", "download"] } },
      },
    ],
    examples: [
      {
        name: "Upload File",
        description: "Upload a file to Backblaze B2",
        parameters: {
          operation: "upload",
          bucketId: "bucket-id",
          fileName: "uploads/file.pdf",
          binaryPropertyName: "data",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.backblaze/",
  },
};
