/**
 * Communication Integration Nodes
 *
 * Slack, Discord, Telegram, Twilio, WhatsApp, Mattermost, Microsoft Teams, etc.
 */

import type { NodeSchema } from "../types.js";

export const COMMUNICATION_NODES: Record<string, NodeSchema> = {
  "n8n-nodes-base.slack": {
    type: "n8n-nodes-base.slack",
    displayName: "Slack",
    description: "Send messages, upload files, and manage Slack workspaces",
    category: "communication",
    typeVersion: 2,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "slackApi", required: true, description: "Slack API credentials (Bot or User token)" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "message",
        description: "Resource to operate on",
        options: [
          { name: "Channel", value: "channel", description: "Manage channels" },
          { name: "Message", value: "message", description: "Send and manage messages" },
          { name: "Reaction", value: "reaction", description: "Add and remove reactions" },
          { name: "Star", value: "star", description: "Star and unstar items" },
          { name: "File", value: "file", description: "Upload and manage files" },
          { name: "User", value: "user", description: "Get user information" },
          { name: "User Group", value: "userGroup", description: "Manage user groups" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "post",
        description: "Operation to perform",
        options: [
          { name: "Post", value: "post", description: "Post a message" },
          { name: "Update", value: "update", description: "Update a message" },
          { name: "Delete", value: "delete", description: "Delete a message" },
          { name: "Get Permalink", value: "getPermalink", description: "Get message permalink" },
          { name: "Search", value: "search", description: "Search messages" },
        ],
        displayOptions: { show: { resource: ["message"] } },
      },
      {
        name: "channel",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Channel to send the message to",
        displayOptions: { show: { resource: ["message"], operation: ["post"] } },
      },
      {
        name: "text",
        type: "string",
        required: false,
        default: "",
        description: "Message text to send (supports markdown)",
        displayOptions: { show: { resource: ["message"], operation: ["post"] } },
      },
      {
        name: "attachments",
        type: "json",
        required: false,
        default: "",
        description: "Message attachments as JSON array",
      },
      {
        name: "blocksUi",
        type: "fixedCollection",
        required: false,
        default: {},
        description: "Block Kit blocks for rich message formatting",
      },
      {
        name: "otherOptions",
        type: "collection",
        required: false,
        default: {},
        description: "Additional options",
      },
    ],
    examples: [
      {
        name: "Post Simple Message",
        description: "Send a text message to a channel",
        parameters: {
          resource: "message",
          operation: "post",
          channel: "#general",
          text: "Hello from n8n!",
        },
      },
      {
        name: "Post with Blocks",
        description: "Send a rich message with Block Kit",
        parameters: {
          resource: "message",
          operation: "post",
          channel: "#general",
          blocksUi: {
            blocksValues: [
              {
                type: "section",
                text: { type: "mrkdwn", text: "*New Alert*\nSomething important happened." },
              },
            ],
          },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.slack/",
  },

  "n8n-nodes-base.discord": {
    type: "n8n-nodes-base.discord",
    displayName: "Discord",
    description: "Send messages and manage Discord servers",
    category: "communication",
    typeVersion: 2,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "discordApi", required: true, description: "Discord Bot or Webhook credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "message",
        description: "Resource to operate on",
        options: [
          { name: "Message", value: "message", description: "Send messages" },
          { name: "Channel", value: "channel", description: "Manage channels" },
          { name: "Member", value: "member", description: "Manage server members" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "send",
        description: "Operation to perform",
        options: [
          { name: "Send", value: "send", description: "Send a message" },
          { name: "Delete", value: "delete", description: "Delete a message" },
        ],
        displayOptions: { show: { resource: ["message"] } },
      },
      {
        name: "guildId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Discord server (guild) ID",
      },
      {
        name: "channelId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Channel ID to send the message to",
        displayOptions: { show: { resource: ["message"] } },
      },
      {
        name: "content",
        type: "string",
        required: false,
        default: "",
        description: "Message content (supports Discord markdown)",
      },
      {
        name: "embeds",
        type: "fixedCollection",
        required: false,
        default: {},
        description: "Rich embed content",
      },
    ],
    examples: [
      {
        name: "Send Simple Message",
        description: "Send a text message to a Discord channel",
        parameters: {
          resource: "message",
          operation: "send",
          channelId: "123456789",
          content: "Hello from n8n!",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.discord/",
  },

  "n8n-nodes-base.telegram": {
    type: "n8n-nodes-base.telegram",
    displayName: "Telegram",
    description: "Send messages, photos, documents via Telegram Bot API",
    category: "communication",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "telegramApi", required: true, description: "Telegram Bot API token" },
    ],
    parameters: [
      {
        name: "operation",
        type: "options",
        required: true,
        default: "sendMessage",
        description: "Operation to perform",
        options: [
          { name: "Send Message", value: "sendMessage", description: "Send a text message" },
          { name: "Send Photo", value: "sendPhoto", description: "Send a photo" },
          { name: "Send Document", value: "sendDocument", description: "Send a document" },
          { name: "Send Audio", value: "sendAudio", description: "Send an audio file" },
          { name: "Send Video", value: "sendVideo", description: "Send a video" },
          { name: "Send Sticker", value: "sendSticker", description: "Send a sticker" },
          { name: "Send Animation", value: "sendAnimation", description: "Send an animation" },
          { name: "Send Location", value: "sendLocation", description: "Send a location" },
          { name: "Send Chat Action", value: "sendChatAction", description: "Send typing indicator" },
          { name: "Edit Message Text", value: "editMessageText", description: "Edit a message" },
          { name: "Delete Message", value: "deleteMessage", description: "Delete a message" },
          { name: "Pin Chat Message", value: "pinChatMessage", description: "Pin a message" },
          { name: "Unpin Chat Message", value: "unpinChatMessage", description: "Unpin a message" },
          { name: "Answer Callback Query", value: "answerQuery", description: "Answer callback query" },
          { name: "Answer Inline Query", value: "answerInlineQuery", description: "Answer inline query" },
          { name: "Get Chat", value: "getChat", description: "Get chat information" },
          { name: "Get File", value: "getFile", description: "Get file by ID" },
          { name: "Get Chat Member", value: "getChatMember", description: "Get chat member info" },
          { name: "Leave Chat", value: "leaveChat", description: "Leave a chat" },
          { name: "Set Chat Description", value: "setChatDescription", description: "Set chat description" },
          { name: "Set Chat Title", value: "setChatTitle", description: "Set chat title" },
        ],
      },
      {
        name: "chatId",
        type: "string",
        required: true,
        default: "",
        description: "Chat ID to send the message to",
      },
      {
        name: "text",
        type: "string",
        required: true,
        default: "",
        description: "Message text (supports HTML or Markdown)",
        displayOptions: { show: { operation: ["sendMessage", "editMessageText"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields",
        options: [
          { name: "parse_mode", value: "parse_mode", description: "Parse mode (HTML or Markdown)" },
          { name: "disable_notification", value: "disable_notification", description: "Silent message" },
          { name: "reply_to_message_id", value: "reply_to_message_id", description: "Reply to message" },
        ],
      },
      {
        name: "replyMarkup",
        type: "options",
        required: false,
        default: "none",
        description: "Reply markup type",
        options: [
          { name: "None", value: "none" },
          { name: "Inline Keyboard", value: "inlineKeyboard" },
          { name: "Reply Keyboard", value: "replyKeyboard" },
          { name: "Reply Keyboard Remove", value: "replyKeyboardRemove" },
          { name: "Force Reply", value: "forceReply" },
        ],
      },
    ],
    examples: [
      {
        name: "Send Text Message",
        description: "Send a simple text message",
        parameters: {
          operation: "sendMessage",
          chatId: "123456789",
          text: "Hello from n8n!",
        },
      },
      {
        name: "Send with Inline Keyboard",
        description: "Send a message with inline buttons",
        parameters: {
          operation: "sendMessage",
          chatId: "123456789",
          text: "Please choose an option:",
          replyMarkup: "inlineKeyboard",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.telegram/",
  },

  "n8n-nodes-base.twilio": {
    type: "n8n-nodes-base.twilio",
    displayName: "Twilio",
    description: "Send SMS, MMS, and make voice calls via Twilio",
    category: "communication",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "twilioApi", required: true, description: "Twilio Account SID and Auth Token" },
    ],
    parameters: [
      {
        name: "operation",
        type: "options",
        required: true,
        default: "send",
        description: "Operation to perform",
        options: [
          { name: "Send SMS", value: "send", description: "Send an SMS message" },
          { name: "Send MMS", value: "sendMms", description: "Send an MMS with media" },
          { name: "Make Call", value: "call", description: "Make a voice call" },
        ],
      },
      {
        name: "from",
        type: "string",
        required: true,
        default: "",
        description: "Twilio phone number to send from",
        placeholder: "+1234567890",
      },
      {
        name: "to",
        type: "string",
        required: true,
        default: "",
        description: "Phone number to send to",
        placeholder: "+1234567890",
      },
      {
        name: "message",
        type: "string",
        required: true,
        default: "",
        description: "Message content",
        displayOptions: { show: { operation: ["send", "sendMms"] } },
      },
      {
        name: "mediaUrl",
        type: "string",
        required: false,
        default: "",
        description: "URL of media to include (MMS)",
        displayOptions: { show: { operation: ["sendMms"] } },
      },
      {
        name: "twiml",
        type: "string",
        required: true,
        default: "",
        description: "TwiML instructions for the call",
        displayOptions: { show: { operation: ["call"] } },
      },
    ],
    examples: [
      {
        name: "Send SMS",
        description: "Send an SMS message",
        parameters: {
          operation: "send",
          from: "+1234567890",
          to: "+0987654321",
          message: "Hello from n8n!",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.twilio/",
  },

  "n8n-nodes-base.whatsApp": {
    type: "n8n-nodes-base.whatsApp",
    displayName: "WhatsApp Business Cloud",
    description: "Send messages via WhatsApp Business Cloud API",
    category: "communication",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "whatsAppApi", required: true, description: "WhatsApp Business API credentials" },
    ],
    parameters: [
      {
        name: "operation",
        type: "options",
        required: true,
        default: "send",
        description: "Operation to perform",
        options: [
          { name: "Send Message", value: "send", description: "Send a text message" },
          { name: "Send Template", value: "sendTemplate", description: "Send a template message" },
          { name: "Send Media", value: "sendMedia", description: "Send media (image, video, document)" },
        ],
      },
      {
        name: "phoneNumberId",
        type: "string",
        required: true,
        default: "",
        description: "WhatsApp Business phone number ID",
      },
      {
        name: "recipientPhoneNumber",
        type: "string",
        required: true,
        default: "",
        description: "Recipient phone number with country code",
        placeholder: "+1234567890",
      },
      {
        name: "textBody",
        type: "string",
        required: true,
        default: "",
        description: "Message text",
        displayOptions: { show: { operation: ["send"] } },
      },
      {
        name: "templateName",
        type: "string",
        required: true,
        default: "",
        description: "Name of the template to send",
        displayOptions: { show: { operation: ["sendTemplate"] } },
      },
    ],
    examples: [
      {
        name: "Send Text Message",
        description: "Send a WhatsApp text message",
        parameters: {
          operation: "send",
          phoneNumberId: "123456789",
          recipientPhoneNumber: "+1234567890",
          textBody: "Hello from n8n!",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.whatsapp/",
  },

  "n8n-nodes-base.mattermost": {
    type: "n8n-nodes-base.mattermost",
    displayName: "Mattermost",
    description: "Send messages and manage Mattermost channels",
    category: "communication",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "mattermostApi", required: true, description: "Mattermost API credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "message",
        description: "Resource to operate on",
        options: [
          { name: "Channel", value: "channel" },
          { name: "Message", value: "message" },
          { name: "Reaction", value: "reaction" },
          { name: "User", value: "user" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "post",
        description: "Operation to perform",
        options: [
          { name: "Post", value: "post", description: "Post a message" },
          { name: "Delete", value: "delete", description: "Delete a message" },
        ],
        displayOptions: { show: { resource: ["message"] } },
      },
      {
        name: "channelId",
        type: "string",
        required: true,
        default: "",
        description: "Channel ID",
        displayOptions: { show: { resource: ["message"], operation: ["post"] } },
      },
      {
        name: "message",
        type: "string",
        required: true,
        default: "",
        description: "Message to post",
        displayOptions: { show: { resource: ["message"], operation: ["post"] } },
      },
    ],
    examples: [
      {
        name: "Post Message",
        description: "Post a message to a channel",
        parameters: {
          resource: "message",
          operation: "post",
          channelId: "abc123",
          message: "Hello from n8n!",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.mattermost/",
  },

  "n8n-nodes-base.microsoftTeams": {
    type: "n8n-nodes-base.microsoftTeams",
    displayName: "Microsoft Teams",
    description: "Send messages and manage Microsoft Teams channels",
    category: "communication",
    typeVersion: 2,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "microsoftTeamsOAuth2Api", required: true, description: "Microsoft OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "chatMessage",
        description: "Resource to operate on",
        options: [
          { name: "Channel", value: "channel" },
          { name: "Channel Message", value: "channelMessage" },
          { name: "Chat", value: "chat" },
          { name: "Chat Message", value: "chatMessage" },
          { name: "Task", value: "task" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a message" },
          { name: "Get", value: "get", description: "Get a message" },
          { name: "Get All", value: "getAll", description: "Get all messages" },
        ],
        displayOptions: { show: { resource: ["chatMessage", "channelMessage"] } },
      },
      {
        name: "teamId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Team ID",
        displayOptions: { show: { resource: ["channelMessage", "channel"] } },
      },
      {
        name: "channelId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Channel ID",
        displayOptions: { show: { resource: ["channelMessage"] } },
      },
      {
        name: "chatId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Chat ID",
        displayOptions: { show: { resource: ["chatMessage"] } },
      },
      {
        name: "messageType",
        type: "options",
        required: true,
        default: "text",
        description: "Message content type",
        options: [
          { name: "Text", value: "text" },
          { name: "HTML", value: "html" },
        ],
      },
      {
        name: "message",
        type: "string",
        required: true,
        default: "",
        description: "Message content",
      },
    ],
    examples: [
      {
        name: "Send Channel Message",
        description: "Send a message to a Teams channel",
        parameters: {
          resource: "channelMessage",
          operation: "create",
          teamId: "team-id",
          channelId: "channel-id",
          messageType: "text",
          message: "Hello from n8n!",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.microsoftteams/",
  },

  "n8n-nodes-base.zulip": {
    type: "n8n-nodes-base.zulip",
    displayName: "Zulip",
    description: "Send messages and manage Zulip chat",
    category: "communication",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "zulipApi", required: true, description: "Zulip API credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "message",
        description: "Resource to operate on",
        options: [
          { name: "Message", value: "message" },
          { name: "Stream", value: "stream" },
          { name: "User", value: "user" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "sendPrivate",
        description: "Operation to perform",
        options: [
          { name: "Send Private", value: "sendPrivate", description: "Send a private message" },
          { name: "Send Stream", value: "sendStream", description: "Send to a stream" },
          { name: "Update", value: "update", description: "Update a message" },
          { name: "Delete", value: "delete", description: "Delete a message" },
        ],
        displayOptions: { show: { resource: ["message"] } },
      },
      {
        name: "to",
        type: "string",
        required: true,
        default: "",
        description: "Recipient (user email for private, stream name for stream)",
      },
      {
        name: "content",
        type: "string",
        required: true,
        default: "",
        description: "Message content (Markdown supported)",
      },
      {
        name: "topic",
        type: "string",
        required: true,
        default: "",
        description: "Topic for stream messages",
        displayOptions: { show: { operation: ["sendStream"] } },
      },
    ],
    examples: [
      {
        name: "Send Stream Message",
        description: "Send a message to a Zulip stream",
        parameters: {
          resource: "message",
          operation: "sendStream",
          to: "general",
          topic: "greetings",
          content: "Hello from n8n!",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.zulip/",
  },

  "n8n-nodes-base.rocketchat": {
    type: "n8n-nodes-base.rocketchat",
    displayName: "Rocket.Chat",
    description: "Send messages and manage Rocket.Chat",
    category: "communication",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "rocketchatApi", required: true, description: "Rocket.Chat API credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "chat",
        description: "Resource to operate on",
        options: [
          { name: "Chat", value: "chat" },
          { name: "Channel", value: "channel" },
          { name: "Group", value: "group" },
          { name: "User", value: "user" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "postMessage",
        description: "Operation to perform",
        options: [
          { name: "Post Message", value: "postMessage", description: "Post a message" },
        ],
        displayOptions: { show: { resource: ["chat"] } },
      },
      {
        name: "channel",
        type: "string",
        required: true,
        default: "",
        description: "Channel name or ID",
      },
      {
        name: "text",
        type: "string",
        required: true,
        default: "",
        description: "Message text",
      },
    ],
    examples: [
      {
        name: "Post Message",
        description: "Post a message to a channel",
        parameters: {
          resource: "chat",
          operation: "postMessage",
          channel: "#general",
          text: "Hello from n8n!",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.rocketchat/",
  },

  "n8n-nodes-base.pushover": {
    type: "n8n-nodes-base.pushover",
    displayName: "Pushover",
    description: "Send push notifications via Pushover",
    category: "communication",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "pushoverApi", required: true, description: "Pushover API credentials" },
    ],
    parameters: [
      {
        name: "userKey",
        type: "string",
        required: true,
        default: "",
        description: "User or group key",
      },
      {
        name: "message",
        type: "string",
        required: true,
        default: "",
        description: "Notification message",
      },
      {
        name: "title",
        type: "string",
        required: false,
        default: "",
        description: "Notification title",
      },
      {
        name: "priority",
        type: "options",
        required: false,
        default: "0",
        description: "Priority level",
        options: [
          { name: "Lowest", value: "-2" },
          { name: "Low", value: "-1" },
          { name: "Normal", value: "0" },
          { name: "High", value: "1" },
          { name: "Emergency", value: "2" },
        ],
      },
      {
        name: "sound",
        type: "options",
        required: false,
        default: "pushover",
        description: "Notification sound",
        options: [
          { name: "Pushover", value: "pushover" },
          { name: "Bike", value: "bike" },
          { name: "Bugle", value: "bugle" },
          { name: "Cash Register", value: "cashregister" },
          { name: "Classical", value: "classical" },
          { name: "Cosmic", value: "cosmic" },
        ],
      },
    ],
    examples: [
      {
        name: "Send Notification",
        description: "Send a push notification",
        parameters: {
          userKey: "user-key",
          message: "Hello from n8n!",
          title: "n8n Notification",
          priority: "0",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.pushover/",
  },

  "n8n-nodes-base.pushbullet": {
    type: "n8n-nodes-base.pushbullet",
    displayName: "Pushbullet",
    description: "Send notifications via Pushbullet",
    category: "communication",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "pushbulletOAuth2Api", required: true, description: "Pushbullet OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "type",
        type: "options",
        required: true,
        default: "note",
        description: "Push type",
        options: [
          { name: "Note", value: "note", description: "Send a note" },
          { name: "Link", value: "link", description: "Send a link" },
          { name: "File", value: "file", description: "Send a file" },
        ],
      },
      {
        name: "title",
        type: "string",
        required: false,
        default: "",
        description: "Push title",
      },
      {
        name: "body",
        type: "string",
        required: false,
        default: "",
        description: "Push body text",
      },
      {
        name: "url",
        type: "string",
        required: true,
        default: "",
        description: "URL to push",
        displayOptions: { show: { type: ["link"] } },
      },
    ],
    examples: [
      {
        name: "Send Note",
        description: "Send a note notification",
        parameters: {
          type: "note",
          title: "n8n Notification",
          body: "Hello from n8n!",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.pushbullet/",
  },

  "n8n-nodes-base.line": {
    type: "n8n-nodes-base.line",
    displayName: "Line",
    description: "Send messages via Line Notify",
    category: "communication",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "lineNotifyOAuth2Api", required: true, description: "Line Notify OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "message",
        type: "string",
        required: true,
        default: "",
        description: "Message to send",
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields",
      },
    ],
    examples: [
      {
        name: "Send Message",
        description: "Send a Line message",
        parameters: {
          message: "Hello from n8n!",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.line/",
  },

  "n8n-nodes-base.zoom": {
    type: "n8n-nodes-base.zoom",
    displayName: "Zoom",
    description: "Manage Zoom meetings, users, and webinars",
    category: "communication",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "zoomOAuth2Api", required: true, description: "Zoom OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "meeting",
        description: "Resource to operate on",
        options: [
          { name: "Meeting", value: "meeting", description: "Manage meetings" },
          { name: "Meeting Registrant", value: "meetingRegistrant", description: "Manage registrants" },
          { name: "User", value: "user", description: "Manage users" },
          { name: "Webinar", value: "webinar", description: "Manage webinars" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a meeting" },
          { name: "Delete", value: "delete", description: "Delete a meeting" },
          { name: "Get", value: "get", description: "Get meeting details" },
          { name: "Get All", value: "getAll", description: "Get all meetings" },
          { name: "Update", value: "update", description: "Update a meeting" },
        ],
        displayOptions: { show: { resource: ["meeting"] } },
      },
      {
        name: "topic",
        type: "string",
        required: true,
        default: "",
        description: "Meeting topic",
        displayOptions: { show: { resource: ["meeting"], operation: ["create"] } },
      },
    ],
    examples: [
      {
        name: "Create Meeting",
        description: "Create a Zoom meeting",
        parameters: {
          resource: "meeting",
          operation: "create",
          topic: "Team Sync",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.zoom/",
  },

  "n8n-nodes-base.webex": {
    type: "n8n-nodes-base.webex",
    displayName: "Webex by Cisco",
    description: "Manage Webex meetings, messages, and teams",
    category: "communication",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "webexOAuth2Api", required: true, description: "Webex OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "meeting",
        description: "Resource to operate on",
        options: [
          { name: "Meeting", value: "meeting", description: "Manage meetings" },
          { name: "Message", value: "message", description: "Manage messages" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a meeting" },
          { name: "Delete", value: "delete", description: "Delete a meeting" },
          { name: "Get", value: "get", description: "Get meeting details" },
          { name: "Get All", value: "getAll", description: "Get all meetings" },
          { name: "Update", value: "update", description: "Update a meeting" },
        ],
        displayOptions: { show: { resource: ["meeting"] } },
      },
      {
        name: "title",
        type: "string",
        required: true,
        default: "",
        description: "Meeting title",
        displayOptions: { show: { resource: ["meeting"], operation: ["create"] } },
      },
    ],
    examples: [
      {
        name: "Create Meeting",
        description: "Create a Webex meeting",
        parameters: {
          resource: "meeting",
          operation: "create",
          title: "Weekly Standup",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.webex/",
  },
};
