/**
 * CRM Integration Nodes
 *
 * Salesforce, HubSpot, Pipedrive, Zoho, Freshsales, etc.
 */

import type { NodeSchema } from "../types.js";

export const CRM_NODES: Record<string, NodeSchema> = {
  "n8n-nodes-base.salesforce": {
    type: "n8n-nodes-base.salesforce",
    displayName: "Salesforce",
    description: "Manage leads, contacts, accounts, and opportunities in Salesforce",
    category: "crm",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "salesforceOAuth2Api", required: true, description: "Salesforce OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "lead",
        description: "Resource to operate on",
        options: [
          { name: "Account", value: "account", description: "Manage accounts" },
          { name: "Attachment", value: "attachment", description: "Manage attachments" },
          { name: "Case", value: "case", description: "Manage cases" },
          { name: "Contact", value: "contact", description: "Manage contacts" },
          { name: "Custom Object", value: "customObject", description: "Manage custom objects" },
          { name: "Document", value: "document", description: "Manage documents" },
          { name: "Flow", value: "flow", description: "Trigger flows" },
          { name: "Lead", value: "lead", description: "Manage leads" },
          { name: "Opportunity", value: "opportunity", description: "Manage opportunities" },
          { name: "Search", value: "search", description: "Search records" },
          { name: "Task", value: "task", description: "Manage tasks" },
          { name: "User", value: "user", description: "Get user information" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a record" },
          { name: "Delete", value: "delete", description: "Delete a record" },
          { name: "Get", value: "get", description: "Get a record" },
          { name: "Get All", value: "getAll", description: "Get all records" },
          { name: "Get Summary", value: "getSummary", description: "Get record summary" },
          { name: "Update", value: "update", description: "Update a record" },
          { name: "Upsert", value: "upsert", description: "Create or update a record" },
        ],
        displayOptions: { show: { resource: ["lead", "contact", "account", "opportunity"] } },
      },
      {
        name: "company",
        type: "string",
        required: true,
        default: "",
        description: "Company name",
        displayOptions: { show: { resource: ["lead"], operation: ["create"] } },
      },
      {
        name: "lastname",
        type: "string",
        required: true,
        default: "",
        description: "Last name",
        displayOptions: { show: { resource: ["lead", "contact"], operation: ["create"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields to set",
      },
    ],
    examples: [
      {
        name: "Create Lead",
        description: "Create a new lead in Salesforce",
        parameters: {
          resource: "lead",
          operation: "create",
          company: "Acme Inc",
          lastname: "Smith",
          additionalFields: { firstName: "John", email: "john@acme.com" },
        },
      },
      {
        name: "Get All Contacts",
        description: "Retrieve all contacts",
        parameters: {
          resource: "contact",
          operation: "getAll",
          returnAll: true,
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.salesforce/",
  },

  "n8n-nodes-base.hubspot": {
    type: "n8n-nodes-base.hubspot",
    displayName: "HubSpot",
    description: "Manage contacts, companies, deals, and tickets in HubSpot",
    category: "crm",
    typeVersion: 2,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "hubspotApi", required: false, description: "HubSpot API key (legacy)" },
      { name: "hubspotOAuth2Api", required: false, description: "HubSpot OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "contact",
        description: "Resource to operate on",
        options: [
          { name: "Company", value: "company", description: "Manage companies" },
          { name: "Contact", value: "contact", description: "Manage contacts" },
          { name: "Contact List", value: "contactList", description: "Manage contact lists" },
          { name: "Deal", value: "deal", description: "Manage deals" },
          { name: "Engagement", value: "engagement", description: "Manage engagements" },
          { name: "Form", value: "form", description: "Submit forms" },
          { name: "Ticket", value: "ticket", description: "Manage tickets" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a contact" },
          { name: "Delete", value: "delete", description: "Delete a contact" },
          { name: "Get", value: "get", description: "Get a contact" },
          { name: "Get All", value: "getAll", description: "Get all contacts" },
          { name: "Get Recently Created", value: "getRecentlyCreatedUpdated", description: "Get recently created contacts" },
          { name: "Search", value: "search", description: "Search contacts" },
          { name: "Update", value: "update", description: "Update a contact" },
        ],
        displayOptions: { show: { resource: ["contact"] } },
      },
      {
        name: "email",
        type: "string",
        required: true,
        default: "",
        description: "Contact email address",
        displayOptions: { show: { resource: ["contact"], operation: ["create"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields to set",
      },
    ],
    examples: [
      {
        name: "Create Contact",
        description: "Create a new contact in HubSpot",
        parameters: {
          resource: "contact",
          operation: "create",
          email: "contact@example.com",
          additionalFields: { firstname: "John", lastname: "Doe" },
        },
      },
      {
        name: "Create Deal",
        description: "Create a new deal",
        parameters: {
          resource: "deal",
          operation: "create",
          additionalFields: { dealname: "New Deal", amount: 10000 },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.hubspot/",
  },

  "n8n-nodes-base.pipedrive": {
    type: "n8n-nodes-base.pipedrive",
    displayName: "Pipedrive",
    description: "Manage deals, contacts, and organizations in Pipedrive",
    category: "crm",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "pipedriveApi", required: false, description: "Pipedrive API token" },
      { name: "pipedriveOAuth2Api", required: false, description: "Pipedrive OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "deal",
        description: "Resource to operate on",
        options: [
          { name: "Activity", value: "activity", description: "Manage activities" },
          { name: "Deal", value: "deal", description: "Manage deals" },
          { name: "Deal Product", value: "dealProduct", description: "Manage deal products" },
          { name: "File", value: "file", description: "Manage files" },
          { name: "Lead", value: "lead", description: "Manage leads" },
          { name: "Note", value: "note", description: "Manage notes" },
          { name: "Organization", value: "organization", description: "Manage organizations" },
          { name: "Person", value: "person", description: "Manage persons/contacts" },
          { name: "Product", value: "product", description: "Manage products" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a record" },
          { name: "Delete", value: "delete", description: "Delete a record" },
          { name: "Get", value: "get", description: "Get a record" },
          { name: "Get All", value: "getAll", description: "Get all records" },
          { name: "Search", value: "search", description: "Search records" },
          { name: "Update", value: "update", description: "Update a record" },
        ],
        displayOptions: { show: { resource: ["deal", "person", "organization"] } },
      },
      {
        name: "title",
        type: "string",
        required: true,
        default: "",
        description: "Deal title",
        displayOptions: { show: { resource: ["deal"], operation: ["create"] } },
      },
      {
        name: "name",
        type: "string",
        required: true,
        default: "",
        description: "Person or organization name",
        displayOptions: { show: { resource: ["person", "organization"], operation: ["create"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields to set",
      },
    ],
    examples: [
      {
        name: "Create Deal",
        description: "Create a new deal in Pipedrive",
        parameters: {
          resource: "deal",
          operation: "create",
          title: "New Business Deal",
          additionalFields: { value: 5000, currency: "USD" },
        },
      },
      {
        name: "Create Person",
        description: "Create a new contact",
        parameters: {
          resource: "person",
          operation: "create",
          name: "John Doe",
          additionalFields: { email: "john@example.com" },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.pipedrive/",
  },

  "n8n-nodes-base.zoho": {
    type: "n8n-nodes-base.zoho",
    displayName: "Zoho CRM",
    description: "Manage leads, contacts, and deals in Zoho CRM",
    category: "crm",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "zohoOAuth2Api", required: true, description: "Zoho OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "lead",
        description: "Resource to operate on",
        options: [
          { name: "Account", value: "account", description: "Manage accounts" },
          { name: "Contact", value: "contact", description: "Manage contacts" },
          { name: "Deal", value: "deal", description: "Manage deals" },
          { name: "Invoice", value: "invoice", description: "Manage invoices" },
          { name: "Lead", value: "lead", description: "Manage leads" },
          { name: "Product", value: "product", description: "Manage products" },
          { name: "Purchase Order", value: "purchaseOrder", description: "Manage purchase orders" },
          { name: "Quote", value: "quote", description: "Manage quotes" },
          { name: "Sales Order", value: "salesOrder", description: "Manage sales orders" },
          { name: "Vendor", value: "vendor", description: "Manage vendors" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a record" },
          { name: "Delete", value: "delete", description: "Delete a record" },
          { name: "Get", value: "get", description: "Get a record" },
          { name: "Get All", value: "getAll", description: "Get all records" },
          { name: "Update", value: "update", description: "Update a record" },
          { name: "Upsert", value: "upsert", description: "Create or update a record" },
        ],
        displayOptions: { show: { resource: ["lead", "contact", "account", "deal"] } },
      },
      {
        name: "lastName",
        type: "string",
        required: true,
        default: "",
        description: "Last name",
        displayOptions: { show: { resource: ["lead", "contact"], operation: ["create"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields to set",
      },
    ],
    examples: [
      {
        name: "Create Lead",
        description: "Create a new lead in Zoho CRM",
        parameters: {
          resource: "lead",
          operation: "create",
          lastName: "Smith",
          additionalFields: { firstName: "John", company: "Acme Inc" },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.zohocrm/",
  },

  "n8n-nodes-base.freshsales": {
    type: "n8n-nodes-base.freshsales",
    displayName: "Freshsales",
    description: "Manage leads, contacts, and deals in Freshsales",
    category: "crm",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "freshsalesApi", required: true, description: "Freshsales API key" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "lead",
        description: "Resource to operate on",
        options: [
          { name: "Account", value: "account" },
          { name: "Appointment", value: "appointment" },
          { name: "Contact", value: "contact" },
          { name: "Deal", value: "deal" },
          { name: "Lead", value: "lead" },
          { name: "Note", value: "note" },
          { name: "Sales Activity", value: "salesActivity" },
          { name: "Task", value: "task" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a record" },
          { name: "Delete", value: "delete", description: "Delete a record" },
          { name: "Get", value: "get", description: "Get a record" },
          { name: "Get All", value: "getAll", description: "Get all records" },
          { name: "Update", value: "update", description: "Update a record" },
        ],
        displayOptions: { show: { resource: ["lead", "contact", "deal"] } },
      },
      {
        name: "email",
        type: "string",
        required: true,
        default: "",
        description: "Email address",
        displayOptions: { show: { resource: ["lead", "contact"], operation: ["create"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields",
      },
    ],
    examples: [
      {
        name: "Create Lead",
        description: "Create a new lead",
        parameters: {
          resource: "lead",
          operation: "create",
          email: "lead@example.com",
          additionalFields: { first_name: "John", last_name: "Doe" },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.freshsales/",
  },

  "n8n-nodes-base.copper": {
    type: "n8n-nodes-base.copper",
    displayName: "Copper",
    description: "Manage leads, people, and opportunities in Copper CRM",
    category: "crm",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "copperApi", required: true, description: "Copper API credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "lead",
        description: "Resource to operate on",
        options: [
          { name: "Company", value: "company" },
          { name: "Customer Source", value: "customerSource" },
          { name: "Lead", value: "lead" },
          { name: "Opportunity", value: "opportunity" },
          { name: "Person", value: "person" },
          { name: "Project", value: "project" },
          { name: "Task", value: "task" },
          { name: "User", value: "user" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create" },
          { name: "Delete", value: "delete" },
          { name: "Get", value: "get" },
          { name: "Get All", value: "getAll" },
          { name: "Update", value: "update" },
        ],
        displayOptions: { show: { resource: ["lead", "person", "company", "opportunity"] } },
      },
      {
        name: "name",
        type: "string",
        required: true,
        default: "",
        description: "Lead name",
        displayOptions: { show: { resource: ["lead"], operation: ["create"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields",
      },
    ],
    examples: [
      {
        name: "Create Lead",
        description: "Create a new lead",
        parameters: {
          resource: "lead",
          operation: "create",
          name: "New Lead",
          additionalFields: { email: { email: "lead@example.com", category: "work" } },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.copper/",
  },

  "n8n-nodes-base.close": {
    type: "n8n-nodes-base.close",
    displayName: "Close",
    description: "Manage leads, contacts, and activities in Close CRM",
    category: "crm",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "closeApi", required: true, description: "Close API key" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "lead",
        description: "Resource to operate on",
        options: [
          { name: "Activity", value: "activity" },
          { name: "Contact", value: "contact" },
          { name: "Custom Activity", value: "customActivity" },
          { name: "Lead", value: "lead" },
          { name: "Opportunity", value: "opportunity" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create" },
          { name: "Delete", value: "delete" },
          { name: "Get", value: "get" },
          { name: "Get All", value: "getAll" },
          { name: "Update", value: "update" },
        ],
        displayOptions: { show: { resource: ["lead", "contact", "opportunity"] } },
      },
      {
        name: "name",
        type: "string",
        required: true,
        default: "",
        description: "Lead name",
        displayOptions: { show: { resource: ["lead"], operation: ["create"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields",
      },
    ],
    examples: [
      {
        name: "Create Lead",
        description: "Create a new lead in Close",
        parameters: {
          resource: "lead",
          operation: "create",
          name: "Acme Corp",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.close/",
  },

  "n8n-nodes-base.activeCampaign": {
    type: "n8n-nodes-base.activeCampaign",
    displayName: "ActiveCampaign",
    description: "Manage contacts, deals, and automations in ActiveCampaign",
    category: "crm",
    subcategory: "marketing",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "activeCampaignApi", required: true, description: "ActiveCampaign API credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "contact",
        description: "Resource to operate on",
        options: [
          { name: "Account", value: "account" },
          { name: "Account Contact", value: "accountContact" },
          { name: "Connection", value: "connection" },
          { name: "Contact", value: "contact" },
          { name: "Contact List", value: "contactList" },
          { name: "Contact Tag", value: "contactTag" },
          { name: "Deal", value: "deal" },
          { name: "Deal Note", value: "dealNote" },
          { name: "E-commerce Order", value: "ecommerceOrder" },
          { name: "E-commerce Order Products", value: "ecommerceOrderProducts" },
          { name: "List", value: "list" },
          { name: "Tag", value: "tag" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create" },
          { name: "Delete", value: "delete" },
          { name: "Get", value: "get" },
          { name: "Get All", value: "getAll" },
          { name: "Update", value: "update" },
        ],
        displayOptions: { show: { resource: ["contact", "deal", "account"] } },
      },
      {
        name: "email",
        type: "string",
        required: true,
        default: "",
        description: "Contact email",
        displayOptions: { show: { resource: ["contact"], operation: ["create"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields",
      },
    ],
    examples: [
      {
        name: "Create Contact",
        description: "Create a new contact",
        parameters: {
          resource: "contact",
          operation: "create",
          email: "contact@example.com",
          additionalFields: { firstName: "John", lastName: "Doe" },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.activecampaign/",
  },

  "n8n-nodes-base.agileCrm": {
    type: "n8n-nodes-base.agileCrm",
    displayName: "Agile CRM",
    description: "Manage contacts, companies, and deals in Agile CRM",
    category: "crm",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "agileCrmApi", required: true, description: "Agile CRM API credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "contact",
        description: "Resource to operate on",
        options: [
          { name: "Company", value: "company" },
          { name: "Contact", value: "contact" },
          { name: "Deal", value: "deal" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create" },
          { name: "Delete", value: "delete" },
          { name: "Get", value: "get" },
          { name: "Get All", value: "getAll" },
          { name: "Update", value: "update" },
        ],
        displayOptions: { show: { resource: ["contact", "company", "deal"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields",
      },
    ],
    examples: [
      {
        name: "Create Contact",
        description: "Create a new contact",
        parameters: {
          resource: "contact",
          operation: "create",
          additionalFields: { email: "contact@example.com" },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.agilecrm/",
  },

  "n8n-nodes-base.highLevel": {
    type: "n8n-nodes-base.highLevel",
    displayName: "HighLevel",
    description: "Manage contacts and opportunities in HighLevel",
    category: "crm",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "highLevelApi", required: true, description: "HighLevel API credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "contact",
        description: "Resource to operate on",
        options: [
          { name: "Contact", value: "contact" },
          { name: "Opportunity", value: "opportunity" },
          { name: "Task", value: "task" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create" },
          { name: "Delete", value: "delete" },
          { name: "Get", value: "get" },
          { name: "Get All", value: "getAll" },
          { name: "Update", value: "update" },
        ],
        displayOptions: { show: { resource: ["contact", "opportunity"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields",
      },
    ],
    examples: [
      {
        name: "Create Contact",
        description: "Create a new contact in HighLevel",
        parameters: {
          resource: "contact",
          operation: "create",
          additionalFields: { email: "contact@example.com" },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.highlevel/",
  },

  "n8n-nodes-base.keap": {
    type: "n8n-nodes-base.keap",
    displayName: "Keap",
    description: "Manage contacts and products in Keap (formerly Infusionsoft)",
    category: "crm",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "keapOAuth2Api", required: true, description: "Keap OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "contact",
        description: "Resource to operate on",
        options: [
          { name: "Company", value: "company" },
          { name: "Contact", value: "contact" },
          { name: "Contact Note", value: "contactNote" },
          { name: "Contact Tag", value: "contactTag" },
          { name: "E-commerce Order", value: "ecommerceOrder" },
          { name: "E-commerce Product", value: "ecommerceProduct" },
          { name: "Email", value: "email" },
          { name: "File", value: "file" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create" },
          { name: "Delete", value: "delete" },
          { name: "Get", value: "get" },
          { name: "Get All", value: "getAll" },
          { name: "Update", value: "update" },
        ],
        displayOptions: { show: { resource: ["contact", "company"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields",
      },
    ],
    examples: [
      {
        name: "Create Contact",
        description: "Create a new contact in Keap",
        parameters: {
          resource: "contact",
          operation: "create",
          additionalFields: { email_addresses: [{ email: "contact@example.com", field: "EMAIL1" }] },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.keap/",
  },

  "n8n-nodes-base.mailerlite": {
    type: "n8n-nodes-base.mailerlite",
    displayName: "MailerLite",
    description: "Manage subscribers in MailerLite",
    category: "crm",
    subcategory: "marketing",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "mailerLiteApi", required: true, description: "MailerLite API key" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "subscriber",
        description: "Resource to operate on",
        options: [
          { name: "Subscriber", value: "subscriber" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create" },
          { name: "Get", value: "get" },
          { name: "Get All", value: "getAll" },
          { name: "Update", value: "update" },
        ],
        displayOptions: { show: { resource: ["subscriber"] } },
      },
      {
        name: "email",
        type: "string",
        required: true,
        default: "",
        description: "Subscriber email",
        displayOptions: { show: { resource: ["subscriber"], operation: ["create"] } },
      },
    ],
    examples: [
      {
        name: "Create Subscriber",
        description: "Add a new subscriber",
        parameters: {
          resource: "subscriber",
          operation: "create",
          email: "subscriber@example.com",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.mailerlite/",
  },

  "n8n-nodes-base.orbit": {
    type: "n8n-nodes-base.orbit",
    displayName: "Orbit",
    description: "Manage community members and activities in Orbit",
    category: "crm",
    subcategory: "community",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "orbitApi", required: true, description: "Orbit API token" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "member",
        description: "Resource to operate on",
        options: [
          { name: "Activity", value: "activity" },
          { name: "Member", value: "member" },
          { name: "Note", value: "note" },
          { name: "Post", value: "post" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create" },
          { name: "Delete", value: "delete" },
          { name: "Get", value: "get" },
          { name: "Get All", value: "getAll" },
          { name: "Lookup", value: "lookup" },
          { name: "Update", value: "update" },
        ],
        displayOptions: { show: { resource: ["member"] } },
      },
      {
        name: "workspaceId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Orbit workspace ID",
      },
    ],
    examples: [
      {
        name: "Create Member",
        description: "Add a new community member",
        parameters: {
          resource: "member",
          operation: "create",
          workspaceId: "workspace-slug",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.orbit/",
  },
};
