/**
 * DevOps Integration Nodes
 *
 * GitHub, GitLab, Bitbucket, Jenkins, CircleCI, Docker, AWS, etc.
 */

import type { NodeSchema } from "../types.js";

export const DEVOPS_NODES: Record<string, NodeSchema> = {
  "n8n-nodes-base.github": {
    type: "n8n-nodes-base.github",
    displayName: "GitHub",
    description: "Manage repositories, issues, and pull requests on GitHub",
    category: "devops",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "githubApi", required: false, description: "GitHub Personal Access Token" },
      { name: "githubOAuth2Api", required: false, description: "GitHub OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "repository",
        description: "Resource to operate on",
        options: [
          { name: "File", value: "file", description: "Manage files" },
          { name: "Issue", value: "issue", description: "Manage issues" },
          { name: "Organization", value: "organization", description: "Manage organizations" },
          { name: "Release", value: "release", description: "Manage releases" },
          { name: "Repository", value: "repository", description: "Manage repositories" },
          { name: "Review", value: "review", description: "Manage PR reviews" },
          { name: "User", value: "user", description: "Manage users" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "get",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create an issue" },
          { name: "Create Comment", value: "createComment", description: "Create a comment" },
          { name: "Edit", value: "edit", description: "Edit an issue" },
          { name: "Get", value: "get", description: "Get an issue" },
          { name: "Lock", value: "lock", description: "Lock an issue" },
        ],
        displayOptions: { show: { resource: ["issue"] } },
      },
      {
        name: "owner",
        type: "string",
        required: true,
        default: "",
        description: "Repository owner",
      },
      {
        name: "repository",
        type: "string",
        required: true,
        default: "",
        description: "Repository name",
      },
      {
        name: "title",
        type: "string",
        required: true,
        default: "",
        description: "Issue title",
        displayOptions: { show: { resource: ["issue"], operation: ["create"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields",
      },
    ],
    examples: [
      {
        name: "Create Issue",
        description: "Create a GitHub issue",
        parameters: {
          resource: "issue",
          operation: "create",
          owner: "owner",
          repository: "repo",
          title: "Bug: Something is broken",
          additionalFields: { body: "Description of the issue" },
        },
      },
      {
        name: "Get Repository",
        description: "Get repository details",
        parameters: {
          resource: "repository",
          operation: "get",
          owner: "owner",
          repository: "repo",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.github/",
  },

  "n8n-nodes-base.gitlab": {
    type: "n8n-nodes-base.gitlab",
    displayName: "GitLab",
    description: "Manage repositories, issues, and merge requests on GitLab",
    category: "devops",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "gitlabApi", required: false, description: "GitLab Personal Access Token" },
      { name: "gitlabOAuth2Api", required: false, description: "GitLab OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "issue",
        description: "Resource to operate on",
        options: [
          { name: "Issue", value: "issue", description: "Manage issues" },
          { name: "Release", value: "release", description: "Manage releases" },
          { name: "Repository", value: "repository", description: "Manage repositories" },
          { name: "User", value: "user", description: "Manage users" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create an issue" },
          { name: "Delete", value: "delete", description: "Delete an issue" },
          { name: "Edit", value: "edit", description: "Edit an issue" },
          { name: "Get", value: "get", description: "Get an issue" },
          { name: "Get All", value: "getAll", description: "Get all issues" },
        ],
        displayOptions: { show: { resource: ["issue"] } },
      },
      {
        name: "projectOwner",
        type: "string",
        required: true,
        default: "",
        description: "Project owner/namespace",
      },
      {
        name: "projectName",
        type: "string",
        required: true,
        default: "",
        description: "Project name",
      },
      {
        name: "title",
        type: "string",
        required: true,
        default: "",
        description: "Issue title",
        displayOptions: { show: { resource: ["issue"], operation: ["create"] } },
      },
    ],
    examples: [
      {
        name: "Create Issue",
        description: "Create a GitLab issue",
        parameters: {
          resource: "issue",
          operation: "create",
          projectOwner: "namespace",
          projectName: "project",
          title: "New Issue",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.gitlab/",
  },

  "n8n-nodes-base.bitbucket": {
    type: "n8n-nodes-base.bitbucket",
    displayName: "Bitbucket",
    description: "Manage repositories on Bitbucket",
    category: "devops",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "bitbucketApi", required: true, description: "Bitbucket credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "repository",
        description: "Resource to operate on",
        options: [
          { name: "Repository", value: "repository" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "get",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a repository" },
          { name: "Delete", value: "delete", description: "Delete a repository" },
          { name: "Get", value: "get", description: "Get a repository" },
          { name: "Get All", value: "getAll", description: "Get all repositories" },
        ],
        displayOptions: { show: { resource: ["repository"] } },
      },
      {
        name: "workspace",
        type: "string",
        required: true,
        default: "",
        description: "Workspace/team slug",
      },
      {
        name: "repositorySlug",
        type: "string",
        required: true,
        default: "",
        description: "Repository slug",
        displayOptions: { show: { operation: ["get", "delete"] } },
      },
    ],
    examples: [
      {
        name: "Get Repository",
        description: "Get repository details",
        parameters: {
          resource: "repository",
          operation: "get",
          workspace: "workspace",
          repositorySlug: "repo-slug",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.bitbucket/",
  },

  "n8n-nodes-base.jenkins": {
    type: "n8n-nodes-base.jenkins",
    displayName: "Jenkins",
    description: "Trigger and manage Jenkins builds",
    category: "devops",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "jenkinsApi", required: true, description: "Jenkins API credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "job",
        description: "Resource to operate on",
        options: [
          { name: "Build", value: "build", description: "Manage builds" },
          { name: "Instance", value: "instance", description: "Get instance info" },
          { name: "Job", value: "job", description: "Manage jobs" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "trigger",
        description: "Operation to perform",
        options: [
          { name: "Copy", value: "copy", description: "Copy a job" },
          { name: "Create", value: "create", description: "Create a job" },
          { name: "Trigger", value: "trigger", description: "Trigger a build" },
          { name: "Trigger with Parameters", value: "triggerParams", description: "Trigger with params" },
        ],
        displayOptions: { show: { resource: ["job"] } },
      },
      {
        name: "job",
        type: "string",
        required: true,
        default: "",
        description: "Job name",
      },
    ],
    examples: [
      {
        name: "Trigger Build",
        description: "Trigger a Jenkins job",
        parameters: {
          resource: "job",
          operation: "trigger",
          job: "my-job",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.jenkins/",
  },

  "n8n-nodes-base.circleCi": {
    type: "n8n-nodes-base.circleCi",
    displayName: "CircleCI",
    description: "Trigger and manage CircleCI pipelines",
    category: "devops",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "circleCiApi", required: true, description: "CircleCI API token" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "pipeline",
        description: "Resource to operate on",
        options: [
          { name: "Pipeline", value: "pipeline", description: "Manage pipelines" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "trigger",
        description: "Operation to perform",
        options: [
          { name: "Get", value: "get", description: "Get a pipeline" },
          { name: "Get All", value: "getAll", description: "Get all pipelines" },
          { name: "Trigger", value: "trigger", description: "Trigger a pipeline" },
        ],
        displayOptions: { show: { resource: ["pipeline"] } },
      },
      {
        name: "vcs",
        type: "options",
        required: true,
        default: "github",
        description: "Version control system",
        options: [
          { name: "Bitbucket", value: "bitbucket" },
          { name: "GitHub", value: "github" },
        ],
        displayOptions: { show: { operation: ["trigger", "getAll"] } },
      },
      {
        name: "projectSlug",
        type: "string",
        required: true,
        default: "",
        description: "Project slug (org/repo)",
      },
      {
        name: "branch",
        type: "string",
        required: true,
        default: "main",
        description: "Branch to build",
        displayOptions: { show: { operation: ["trigger"] } },
      },
    ],
    examples: [
      {
        name: "Trigger Pipeline",
        description: "Trigger a CircleCI pipeline",
        parameters: {
          resource: "pipeline",
          operation: "trigger",
          vcs: "github",
          projectSlug: "org/repo",
          branch: "main",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.circleci/",
  },

  "n8n-nodes-base.docker": {
    type: "n8n-nodes-base.docker",
    displayName: "Docker",
    description: "Manage Docker containers and images",
    category: "devops",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "dockerApi", required: true, description: "Docker API credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "container",
        description: "Resource to operate on",
        options: [
          { name: "Container", value: "container", description: "Manage containers" },
          { name: "Image", value: "image", description: "Manage images" },
          { name: "Network", value: "network", description: "Manage networks" },
          { name: "Volume", value: "volume", description: "Manage volumes" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "list",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a container" },
          { name: "Delete", value: "delete", description: "Delete a container" },
          { name: "Get", value: "get", description: "Get a container" },
          { name: "List", value: "list", description: "List containers" },
          { name: "Restart", value: "restart", description: "Restart a container" },
          { name: "Start", value: "start", description: "Start a container" },
          { name: "Stop", value: "stop", description: "Stop a container" },
        ],
        displayOptions: { show: { resource: ["container"] } },
      },
      {
        name: "containerId",
        type: "string",
        required: true,
        default: "",
        description: "Container ID or name",
        displayOptions: { show: { resource: ["container"], operation: ["get", "delete", "start", "stop", "restart"] } },
      },
    ],
    examples: [
      {
        name: "List Containers",
        description: "List all Docker containers",
        parameters: {
          resource: "container",
          operation: "list",
        },
      },
      {
        name: "Start Container",
        description: "Start a container",
        parameters: {
          resource: "container",
          operation: "start",
          containerId: "container-name",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.docker/",
  },

  "n8n-nodes-base.awsLambda": {
    type: "n8n-nodes-base.awsLambda",
    displayName: "AWS Lambda",
    description: "Invoke AWS Lambda functions",
    category: "devops",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "aws", required: true, description: "AWS credentials" },
    ],
    parameters: [
      {
        name: "operation",
        type: "options",
        required: true,
        default: "invoke",
        description: "Operation to perform",
        options: [
          { name: "Invoke", value: "invoke", description: "Invoke a Lambda function" },
        ],
      },
      {
        name: "function",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Lambda function name or ARN",
      },
      {
        name: "invocationType",
        type: "options",
        required: true,
        default: "RequestResponse",
        description: "Invocation type",
        options: [
          { name: "Request Response", value: "RequestResponse", description: "Synchronous" },
          { name: "Event", value: "Event", description: "Asynchronous" },
          { name: "Dry Run", value: "DryRun", description: "Test invocation" },
        ],
      },
      {
        name: "payload",
        type: "json",
        required: false,
        default: "{}",
        description: "JSON payload to send",
      },
    ],
    examples: [
      {
        name: "Invoke Function",
        description: "Invoke a Lambda function",
        parameters: {
          operation: "invoke",
          function: "my-function",
          invocationType: "RequestResponse",
          payload: '{"key": "value"}',
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.awslambda/",
  },

  "n8n-nodes-base.awsSns": {
    type: "n8n-nodes-base.awsSns",
    displayName: "AWS SNS",
    description: "Publish messages to AWS SNS topics",
    category: "devops",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "aws", required: true, description: "AWS credentials" },
    ],
    parameters: [
      {
        name: "operation",
        type: "options",
        required: true,
        default: "publish",
        description: "Operation to perform",
        options: [
          { name: "Create Topic", value: "create", description: "Create an SNS topic" },
          { name: "Delete Topic", value: "delete", description: "Delete an SNS topic" },
          { name: "Publish", value: "publish", description: "Publish a message" },
        ],
      },
      {
        name: "topic",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "SNS topic ARN",
        displayOptions: { show: { operation: ["publish", "delete"] } },
      },
      {
        name: "subject",
        type: "string",
        required: false,
        default: "",
        description: "Message subject (email subscriptions)",
        displayOptions: { show: { operation: ["publish"] } },
      },
      {
        name: "message",
        type: "string",
        required: true,
        default: "",
        description: "Message content",
        displayOptions: { show: { operation: ["publish"] } },
      },
    ],
    examples: [
      {
        name: "Publish Message",
        description: "Publish a message to SNS",
        parameters: {
          operation: "publish",
          topic: "arn:aws:sns:region:account:topic-name",
          message: "Hello from n8n!",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.awssns/",
  },

  "n8n-nodes-base.awsSqs": {
    type: "n8n-nodes-base.awsSqs",
    displayName: "AWS SQS",
    description: "Send and receive messages from AWS SQS queues",
    category: "devops",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "aws", required: true, description: "AWS credentials" },
    ],
    parameters: [
      {
        name: "operation",
        type: "options",
        required: true,
        default: "sendMessage",
        description: "Operation to perform",
        options: [
          { name: "Delete Message", value: "deleteMessage", description: "Delete a message" },
          { name: "Get Queue Attributes", value: "getQueueAttributes", description: "Get queue attributes" },
          { name: "Receive Message", value: "receiveMessage", description: "Receive messages" },
          { name: "Send Message", value: "sendMessage", description: "Send a message" },
        ],
      },
      {
        name: "queue",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "SQS queue URL",
      },
      {
        name: "messageBody",
        type: "string",
        required: true,
        default: "",
        description: "Message body",
        displayOptions: { show: { operation: ["sendMessage"] } },
      },
      {
        name: "options",
        type: "collection",
        required: false,
        default: {},
        description: "Additional options",
      },
    ],
    examples: [
      {
        name: "Send Message",
        description: "Send a message to SQS",
        parameters: {
          operation: "sendMessage",
          queue: "https://sqs.region.amazonaws.com/account/queue-name",
          messageBody: '{"event": "test"}',
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.awssqs/",
  },

  "n8n-nodes-base.kubernetes": {
    type: "n8n-nodes-base.kubernetes",
    displayName: "Kubernetes",
    description: "Manage Kubernetes resources",
    category: "devops",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "kubernetes", required: true, description: "Kubernetes credentials" },
    ],
    parameters: [
      {
        name: "operation",
        type: "options",
        required: true,
        default: "get",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a resource" },
          { name: "Delete", value: "delete", description: "Delete a resource" },
          { name: "Get", value: "get", description: "Get a resource" },
          { name: "Get All", value: "getAll", description: "Get all resources" },
        ],
      },
      {
        name: "resourceType",
        type: "options",
        required: true,
        default: "pod",
        description: "Resource type",
        options: [
          { name: "Config Map", value: "configMap" },
          { name: "Deployment", value: "deployment" },
          { name: "Job", value: "job" },
          { name: "Namespace", value: "namespace" },
          { name: "Pod", value: "pod" },
          { name: "Secret", value: "secret" },
          { name: "Service", value: "service" },
        ],
      },
      {
        name: "namespace",
        type: "string",
        required: true,
        default: "default",
        description: "Kubernetes namespace",
      },
      {
        name: "name",
        type: "string",
        required: true,
        default: "",
        description: "Resource name",
        displayOptions: { show: { operation: ["get", "delete"] } },
      },
    ],
    examples: [
      {
        name: "Get Pods",
        description: "Get all pods in namespace",
        parameters: {
          operation: "getAll",
          resourceType: "pod",
          namespace: "default",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.kubernetes/",
  },

  "n8n-nodes-base.sentry": {
    type: "n8n-nodes-base.sentry",
    displayName: "Sentry",
    description: "Manage issues and releases in Sentry",
    category: "devops",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "sentryIoApi", required: false, description: "Sentry API token" },
      { name: "sentryIoOAuth2Api", required: false, description: "Sentry OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "issue",
        description: "Resource to operate on",
        options: [
          { name: "Event", value: "event", description: "Get events" },
          { name: "Issue", value: "issue", description: "Manage issues" },
          { name: "Organization", value: "organization", description: "Manage organizations" },
          { name: "Project", value: "project", description: "Manage projects" },
          { name: "Release", value: "release", description: "Manage releases" },
          { name: "Team", value: "team", description: "Manage teams" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "get",
        description: "Operation to perform",
        options: [
          { name: "Delete", value: "delete", description: "Delete an issue" },
          { name: "Get", value: "get", description: "Get an issue" },
          { name: "Get All", value: "getAll", description: "Get all issues" },
          { name: "Update", value: "update", description: "Update an issue" },
        ],
        displayOptions: { show: { resource: ["issue"] } },
      },
      {
        name: "organizationSlug",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Organization slug",
      },
      {
        name: "projectSlug",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Project slug",
        displayOptions: { show: { resource: ["issue", "event", "release"] } },
      },
    ],
    examples: [
      {
        name: "Get Issues",
        description: "Get all issues for a project",
        parameters: {
          resource: "issue",
          operation: "getAll",
          organizationSlug: "my-org",
          projectSlug: "my-project",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.sentryio/",
  },

  "n8n-nodes-base.pagerDuty": {
    type: "n8n-nodes-base.pagerDuty",
    displayName: "PagerDuty",
    description: "Create and manage incidents in PagerDuty",
    category: "devops",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "pagerDutyApi", required: false, description: "PagerDuty API token" },
      { name: "pagerDutyOAuth2Api", required: false, description: "PagerDuty OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "incident",
        description: "Resource to operate on",
        options: [
          { name: "Incident", value: "incident", description: "Manage incidents" },
          { name: "Incident Note", value: "incidentNote", description: "Manage notes" },
          { name: "Log Entry", value: "logEntry", description: "Get log entries" },
          { name: "User", value: "user", description: "Manage users" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create an incident" },
          { name: "Get", value: "get", description: "Get an incident" },
          { name: "Get All", value: "getAll", description: "Get all incidents" },
          { name: "Update", value: "update", description: "Update an incident" },
        ],
        displayOptions: { show: { resource: ["incident"] } },
      },
      {
        name: "title",
        type: "string",
        required: true,
        default: "",
        description: "Incident title",
        displayOptions: { show: { resource: ["incident"], operation: ["create"] } },
      },
      {
        name: "serviceId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Service ID",
        displayOptions: { show: { resource: ["incident"], operation: ["create"] } },
      },
    ],
    examples: [
      {
        name: "Create Incident",
        description: "Create a PagerDuty incident",
        parameters: {
          resource: "incident",
          operation: "create",
          title: "Server Down",
          serviceId: "service-id",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.pagerduty/",
  },

  "n8n-nodes-base.datadog": {
    type: "n8n-nodes-base.datadog",
    displayName: "Datadog",
    description: "Send metrics and events to Datadog",
    category: "devops",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "datadogApi", required: true, description: "Datadog API credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "event",
        description: "Resource to operate on",
        options: [
          { name: "Event", value: "event", description: "Send events" },
          { name: "Metric", value: "metric", description: "Send metrics" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create an event" },
        ],
        displayOptions: { show: { resource: ["event"] } },
      },
      {
        name: "title",
        type: "string",
        required: true,
        default: "",
        description: "Event title",
        displayOptions: { show: { resource: ["event"], operation: ["create"] } },
      },
      {
        name: "text",
        type: "string",
        required: true,
        default: "",
        description: "Event text",
        displayOptions: { show: { resource: ["event"], operation: ["create"] } },
      },
    ],
    examples: [
      {
        name: "Send Event",
        description: "Send an event to Datadog",
        parameters: {
          resource: "event",
          operation: "create",
          title: "Deployment Complete",
          text: "Application deployed successfully",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.datadog/",
  },

  "n8n-nodes-base.grafana": {
    type: "n8n-nodes-base.grafana",
    displayName: "Grafana",
    description: "Manage Grafana dashboards and annotations",
    category: "devops",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "grafanaApi", required: true, description: "Grafana API credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "dashboard",
        description: "Resource to operate on",
        options: [
          { name: "Dashboard", value: "dashboard", description: "Manage dashboards" },
          { name: "Team", value: "team", description: "Manage teams" },
          { name: "Team Member", value: "teamMember", description: "Manage team members" },
          { name: "User", value: "user", description: "Manage users" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "get",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a dashboard" },
          { name: "Delete", value: "delete", description: "Delete a dashboard" },
          { name: "Get", value: "get", description: "Get a dashboard" },
          { name: "Get All", value: "getAll", description: "Get all dashboards" },
          { name: "Update", value: "update", description: "Update a dashboard" },
        ],
        displayOptions: { show: { resource: ["dashboard"] } },
      },
    ],
    examples: [
      {
        name: "Get Dashboards",
        description: "Get all Grafana dashboards",
        parameters: {
          resource: "dashboard",
          operation: "getAll",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.grafana/",
  },
};
