/**
 * Email Integration Nodes
 *
 * Gmail, SendGrid, Mailchimp, Mailgun, SMTP, Outlook, etc.
 */

import type { NodeSchema } from "../types.js";

export const EMAIL_NODES: Record<string, NodeSchema> = {
  "n8n-nodes-base.gmail": {
    type: "n8n-nodes-base.gmail",
    displayName: "Gmail",
    description: "Send, read, and manage emails via Gmail API",
    category: "email",
    typeVersion: 2,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "gmailOAuth2", required: true, description: "Gmail OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "message",
        description: "Resource to operate on",
        options: [
          { name: "Draft", value: "draft", description: "Create and manage drafts" },
          { name: "Label", value: "label", description: "Manage labels" },
          { name: "Message", value: "message", description: "Send and manage messages" },
          { name: "Thread", value: "thread", description: "Manage threads" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "send",
        description: "Operation to perform",
        options: [
          { name: "Send", value: "send", description: "Send an email" },
          { name: "Reply", value: "reply", description: "Reply to an email" },
          { name: "Get", value: "get", description: "Get an email" },
          { name: "Get Many", value: "getAll", description: "Get multiple emails" },
          { name: "Delete", value: "delete", description: "Delete an email" },
          { name: "Add Label", value: "addLabels", description: "Add labels" },
          { name: "Remove Label", value: "removeLabels", description: "Remove labels" },
          { name: "Mark as Read", value: "markAsRead", description: "Mark as read" },
          { name: "Mark as Unread", value: "markAsUnread", description: "Mark as unread" },
        ],
        displayOptions: { show: { resource: ["message"] } },
      },
      {
        name: "sendTo",
        type: "string",
        required: true,
        default: "",
        description: "Email recipient",
        placeholder: "recipient@example.com",
        displayOptions: { show: { resource: ["message"], operation: ["send"] } },
      },
      {
        name: "subject",
        type: "string",
        required: true,
        default: "",
        description: "Email subject",
        displayOptions: { show: { resource: ["message"], operation: ["send"] } },
      },
      {
        name: "emailType",
        type: "options",
        required: true,
        default: "text",
        description: "Email content type",
        options: [
          { name: "Text", value: "text" },
          { name: "HTML", value: "html" },
        ],
        displayOptions: { show: { resource: ["message"], operation: ["send"] } },
      },
      {
        name: "message",
        type: "string",
        required: true,
        default: "",
        description: "Email body content",
        displayOptions: { show: { resource: ["message"], operation: ["send"] } },
      },
      {
        name: "options",
        type: "collection",
        required: false,
        default: {},
        description: "Additional options",
        options: [
          { name: "ccEmail", value: "ccEmail", description: "CC recipients" },
          { name: "bccEmail", value: "bccEmail", description: "BCC recipients" },
          { name: "replyTo", value: "replyTo", description: "Reply-to address" },
          { name: "senderName", value: "senderName", description: "Sender name" },
        ],
      },
      {
        name: "attachmentsUi",
        type: "fixedCollection",
        required: false,
        default: {},
        description: "Attachments to include",
      },
    ],
    examples: [
      {
        name: "Send Email",
        description: "Send a simple email",
        parameters: {
          resource: "message",
          operation: "send",
          sendTo: "recipient@example.com",
          subject: "Hello from n8n",
          emailType: "text",
          message: "This is a test email from n8n.",
        },
      },
      {
        name: "Get Recent Emails",
        description: "Retrieve recent emails from inbox",
        parameters: {
          resource: "message",
          operation: "getAll",
          returnAll: false,
          limit: 10,
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.gmail/",
  },

  "n8n-nodes-base.microsoftOutlook": {
    type: "n8n-nodes-base.microsoftOutlook",
    displayName: "Microsoft Outlook",
    description: "Send and manage emails via Microsoft Outlook",
    category: "email",
    typeVersion: 2,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "microsoftOutlookOAuth2Api", required: true, description: "Microsoft OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "message",
        description: "Resource to operate on",
        options: [
          { name: "Calendar", value: "calendar" },
          { name: "Contact", value: "contact" },
          { name: "Draft", value: "draft" },
          { name: "Event", value: "event" },
          { name: "Folder", value: "folder" },
          { name: "Message", value: "message" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "send",
        description: "Operation to perform",
        options: [
          { name: "Send", value: "send", description: "Send an email" },
          { name: "Reply", value: "reply", description: "Reply to an email" },
          { name: "Get", value: "get", description: "Get an email" },
          { name: "Get Many", value: "getAll", description: "Get many emails" },
          { name: "Delete", value: "delete", description: "Delete an email" },
          { name: "Move", value: "move", description: "Move to folder" },
        ],
        displayOptions: { show: { resource: ["message"] } },
      },
      {
        name: "toRecipients",
        type: "string",
        required: true,
        default: "",
        description: "Email recipients (comma-separated)",
        displayOptions: { show: { resource: ["message"], operation: ["send"] } },
      },
      {
        name: "subject",
        type: "string",
        required: true,
        default: "",
        description: "Email subject",
        displayOptions: { show: { resource: ["message"], operation: ["send"] } },
      },
      {
        name: "bodyContent",
        type: "string",
        required: true,
        default: "",
        description: "Email body content",
        displayOptions: { show: { resource: ["message"], operation: ["send"] } },
      },
    ],
    examples: [
      {
        name: "Send Email",
        description: "Send an email via Outlook",
        parameters: {
          resource: "message",
          operation: "send",
          toRecipients: "recipient@example.com",
          subject: "Hello from n8n",
          bodyContent: "This is a test email.",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.microsoftoutlook/",
  },

  "n8n-nodes-base.sendGrid": {
    type: "n8n-nodes-base.sendGrid",
    displayName: "SendGrid",
    description: "Send emails and manage contacts via SendGrid",
    category: "email",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "sendGridApi", required: true, description: "SendGrid API key" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "mail",
        description: "Resource to operate on",
        options: [
          { name: "Contact", value: "contact", description: "Manage contacts" },
          { name: "List", value: "list", description: "Manage lists" },
          { name: "Mail", value: "mail", description: "Send emails" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "send",
        description: "Operation to perform",
        options: [
          { name: "Send", value: "send", description: "Send an email" },
        ],
        displayOptions: { show: { resource: ["mail"] } },
      },
      {
        name: "fromEmail",
        type: "string",
        required: true,
        default: "",
        description: "Sender email address",
        displayOptions: { show: { resource: ["mail"] } },
      },
      {
        name: "toEmail",
        type: "string",
        required: true,
        default: "",
        description: "Recipient email address",
        displayOptions: { show: { resource: ["mail"] } },
      },
      {
        name: "subject",
        type: "string",
        required: true,
        default: "",
        description: "Email subject",
        displayOptions: { show: { resource: ["mail"] } },
      },
      {
        name: "contentType",
        type: "options",
        required: true,
        default: "text/plain",
        description: "Content type",
        options: [
          { name: "Plain Text", value: "text/plain" },
          { name: "HTML", value: "text/html" },
        ],
        displayOptions: { show: { resource: ["mail"] } },
      },
      {
        name: "contentValue",
        type: "string",
        required: true,
        default: "",
        description: "Email content",
        displayOptions: { show: { resource: ["mail"] } },
      },
      {
        name: "dynamicTemplateData",
        type: "json",
        required: false,
        default: "",
        description: "Dynamic template data as JSON",
      },
    ],
    examples: [
      {
        name: "Send Email",
        description: "Send a transactional email",
        parameters: {
          resource: "mail",
          operation: "send",
          fromEmail: "sender@example.com",
          toEmail: "recipient@example.com",
          subject: "Hello from n8n",
          contentType: "text/plain",
          contentValue: "This is a test email.",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.sendgrid/",
  },

  "n8n-nodes-base.mailchimp": {
    type: "n8n-nodes-base.mailchimp",
    displayName: "Mailchimp",
    description: "Manage subscribers, lists, and campaigns in Mailchimp",
    category: "email",
    subcategory: "marketing",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "mailchimpApi", required: true, description: "Mailchimp API key" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "member",
        description: "Resource to operate on",
        options: [
          { name: "Campaign", value: "campaign", description: "Manage campaigns" },
          { name: "List/Audience", value: "listGroup", description: "Manage lists" },
          { name: "Member", value: "member", description: "Manage subscribers" },
          { name: "Member Tag", value: "memberTag", description: "Manage member tags" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a member" },
          { name: "Delete", value: "delete", description: "Delete a member" },
          { name: "Get", value: "get", description: "Get a member" },
          { name: "Get All", value: "getAll", description: "Get all members" },
          { name: "Update", value: "update", description: "Update a member" },
        ],
        displayOptions: { show: { resource: ["member"] } },
      },
      {
        name: "list",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "List/audience ID",
      },
      {
        name: "email",
        type: "string",
        required: true,
        default: "",
        description: "Email address of the subscriber",
        displayOptions: { show: { resource: ["member"] } },
      },
      {
        name: "status",
        type: "options",
        required: true,
        default: "subscribed",
        description: "Subscription status",
        options: [
          { name: "Subscribed", value: "subscribed" },
          { name: "Unsubscribed", value: "unsubscribed" },
          { name: "Cleaned", value: "cleaned" },
          { name: "Pending", value: "pending" },
          { name: "Transactional", value: "transactional" },
        ],
        displayOptions: { show: { resource: ["member"], operation: ["create"] } },
      },
      {
        name: "mergeFields",
        type: "fixedCollection",
        required: false,
        default: {},
        description: "Merge fields (FNAME, LNAME, etc.)",
      },
    ],
    examples: [
      {
        name: "Add Subscriber",
        description: "Add a new subscriber to a list",
        parameters: {
          resource: "member",
          operation: "create",
          list: "list-id",
          email: "subscriber@example.com",
          status: "subscribed",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.mailchimp/",
  },

  "n8n-nodes-base.mailgun": {
    type: "n8n-nodes-base.mailgun",
    displayName: "Mailgun",
    description: "Send emails via Mailgun API",
    category: "email",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "mailgunApi", required: true, description: "Mailgun API key and domain" },
    ],
    parameters: [
      {
        name: "from",
        type: "string",
        required: true,
        default: "",
        description: "Sender email address",
        placeholder: "sender@example.com",
      },
      {
        name: "to",
        type: "string",
        required: true,
        default: "",
        description: "Recipient email addresses (comma-separated)",
      },
      {
        name: "subject",
        type: "string",
        required: true,
        default: "",
        description: "Email subject",
      },
      {
        name: "text",
        type: "string",
        required: false,
        default: "",
        description: "Plain text body",
      },
      {
        name: "html",
        type: "string",
        required: false,
        default: "",
        description: "HTML body",
      },
      {
        name: "attachments",
        type: "string",
        required: false,
        default: "",
        description: "Binary property name for attachments",
      },
    ],
    examples: [
      {
        name: "Send Email",
        description: "Send an email via Mailgun",
        parameters: {
          from: "sender@example.com",
          to: "recipient@example.com",
          subject: "Hello from n8n",
          text: "This is a test email.",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.mailgun/",
  },

  "n8n-nodes-base.mailjet": {
    type: "n8n-nodes-base.mailjet",
    displayName: "Mailjet",
    description: "Send emails and manage contacts via Mailjet",
    category: "email",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "mailjetEmailApi", required: true, description: "Mailjet API credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "email",
        description: "Resource to operate on",
        options: [
          { name: "Contact", value: "contact" },
          { name: "Email", value: "email" },
          { name: "SMS", value: "sms" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "send",
        description: "Operation to perform",
        options: [
          { name: "Send", value: "send", description: "Send an email" },
          { name: "Send Template", value: "sendTemplate", description: "Send using template" },
        ],
        displayOptions: { show: { resource: ["email"] } },
      },
      {
        name: "fromEmail",
        type: "string",
        required: true,
        default: "",
        description: "Sender email",
        displayOptions: { show: { resource: ["email"] } },
      },
      {
        name: "toEmail",
        type: "string",
        required: true,
        default: "",
        description: "Recipient email",
        displayOptions: { show: { resource: ["email"] } },
      },
      {
        name: "subject",
        type: "string",
        required: true,
        default: "",
        description: "Email subject",
        displayOptions: { show: { resource: ["email"], operation: ["send"] } },
      },
      {
        name: "textPart",
        type: "string",
        required: false,
        default: "",
        description: "Plain text content",
      },
      {
        name: "htmlPart",
        type: "string",
        required: false,
        default: "",
        description: "HTML content",
      },
    ],
    examples: [
      {
        name: "Send Email",
        description: "Send an email via Mailjet",
        parameters: {
          resource: "email",
          operation: "send",
          fromEmail: "sender@example.com",
          toEmail: "recipient@example.com",
          subject: "Hello from n8n",
          textPart: "This is a test email.",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.mailjet/",
  },

  "n8n-nodes-base.awsSes": {
    type: "n8n-nodes-base.awsSes",
    displayName: "AWS SES",
    description: "Send emails via Amazon Simple Email Service",
    category: "email",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "aws", required: true, description: "AWS credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "email",
        description: "Resource to operate on",
        options: [
          { name: "Custom Verification Email", value: "customVerificationEmail" },
          { name: "Email", value: "email" },
          { name: "Template", value: "template" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "send",
        description: "Operation to perform",
        options: [
          { name: "Send", value: "send", description: "Send an email" },
          { name: "Send Template", value: "sendTemplate", description: "Send templated email" },
        ],
        displayOptions: { show: { resource: ["email"] } },
      },
      {
        name: "fromEmail",
        type: "string",
        required: true,
        default: "",
        description: "Verified sender email",
      },
      {
        name: "toAddresses",
        type: "string",
        required: true,
        default: "",
        description: "Recipient addresses (comma-separated)",
      },
      {
        name: "subject",
        type: "string",
        required: true,
        default: "",
        description: "Email subject",
        displayOptions: { show: { resource: ["email"], operation: ["send"] } },
      },
      {
        name: "body",
        type: "string",
        required: true,
        default: "",
        description: "Email body",
        displayOptions: { show: { resource: ["email"], operation: ["send"] } },
      },
    ],
    examples: [
      {
        name: "Send Email",
        description: "Send an email via AWS SES",
        parameters: {
          resource: "email",
          operation: "send",
          fromEmail: "verified@example.com",
          toAddresses: "recipient@example.com",
          subject: "Hello from n8n",
          body: "This is a test email.",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.awsses/",
  },

  "n8n-nodes-base.emailSend": {
    type: "n8n-nodes-base.emailSend",
    displayName: "Send Email",
    description: "Send emails via SMTP",
    category: "email",
    typeVersion: 2,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "smtp", required: true, description: "SMTP server credentials" },
    ],
    parameters: [
      {
        name: "fromEmail",
        type: "string",
        required: true,
        default: "",
        description: "Sender email address",
        placeholder: "sender@example.com",
      },
      {
        name: "toEmail",
        type: "string",
        required: true,
        default: "",
        description: "Recipient email addresses (comma-separated)",
      },
      {
        name: "subject",
        type: "string",
        required: true,
        default: "",
        description: "Email subject",
      },
      {
        name: "emailFormat",
        type: "options",
        required: true,
        default: "text",
        description: "Email format",
        options: [
          { name: "Text", value: "text" },
          { name: "HTML", value: "html" },
          { name: "Both", value: "both" },
        ],
      },
      {
        name: "text",
        type: "string",
        required: true,
        default: "",
        description: "Plain text content",
        displayOptions: { show: { emailFormat: ["text", "both"] } },
      },
      {
        name: "html",
        type: "string",
        required: true,
        default: "",
        description: "HTML content",
        displayOptions: { show: { emailFormat: ["html", "both"] } },
      },
      {
        name: "options",
        type: "collection",
        required: false,
        default: {},
        description: "Additional options",
        options: [
          { name: "ccEmail", value: "ccEmail", description: "CC recipients" },
          { name: "bccEmail", value: "bccEmail", description: "BCC recipients" },
          { name: "replyTo", value: "replyTo", description: "Reply-to address" },
          { name: "attachments", value: "attachments", description: "Attachments" },
        ],
      },
    ],
    examples: [
      {
        name: "Send SMTP Email",
        description: "Send an email via SMTP",
        parameters: {
          fromEmail: "sender@example.com",
          toEmail: "recipient@example.com",
          subject: "Hello from n8n",
          emailFormat: "text",
          text: "This is a test email.",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.emailsend/",
  },

  "n8n-nodes-base.emailReadImap": {
    type: "n8n-nodes-base.emailReadImap",
    displayName: "Email (IMAP)",
    description: "Read emails from IMAP server",
    category: "email",
    typeVersion: 2,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "imap", required: true, description: "IMAP server credentials" },
    ],
    parameters: [
      {
        name: "mailbox",
        type: "string",
        required: true,
        default: "INBOX",
        description: "Mailbox to read from",
      },
      {
        name: "postProcessAction",
        type: "options",
        required: true,
        default: "nothing",
        description: "Action after reading email",
        options: [
          { name: "Nothing", value: "nothing" },
          { name: "Mark as Read", value: "read" },
          { name: "Delete", value: "delete" },
        ],
      },
      {
        name: "options",
        type: "collection",
        required: false,
        default: {},
        description: "Additional options",
      },
    ],
    examples: [
      {
        name: "Read Inbox",
        description: "Read emails from inbox",
        parameters: {
          mailbox: "INBOX",
          postProcessAction: "read",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.emailreadimap/",
  },

  "n8n-nodes-base.postmark": {
    type: "n8n-nodes-base.postmark",
    displayName: "Postmark",
    description: "Send transactional emails via Postmark",
    category: "email",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "postmarkApi", required: true, description: "Postmark API token" },
    ],
    parameters: [
      {
        name: "fromEmail",
        type: "string",
        required: true,
        default: "",
        description: "Verified sender email",
      },
      {
        name: "toEmail",
        type: "string",
        required: true,
        default: "",
        description: "Recipient email",
      },
      {
        name: "subject",
        type: "string",
        required: true,
        default: "",
        description: "Email subject",
      },
      {
        name: "htmlBody",
        type: "string",
        required: false,
        default: "",
        description: "HTML body",
      },
      {
        name: "textBody",
        type: "string",
        required: false,
        default: "",
        description: "Plain text body",
      },
    ],
    examples: [
      {
        name: "Send Email",
        description: "Send an email via Postmark",
        parameters: {
          fromEmail: "sender@example.com",
          toEmail: "recipient@example.com",
          subject: "Hello from n8n",
          textBody: "This is a test email.",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.postmark/",
  },

  "n8n-nodes-base.customerIo": {
    type: "n8n-nodes-base.customerIo",
    displayName: "Customer.io",
    description: "Manage customers and send emails via Customer.io",
    category: "email",
    subcategory: "marketing",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "customerIoApi", required: true, description: "Customer.io API credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "customer",
        description: "Resource to operate on",
        options: [
          { name: "Campaign", value: "campaign" },
          { name: "Customer", value: "customer" },
          { name: "Event", value: "event" },
          { name: "Segment", value: "segment" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "upsert",
        description: "Operation to perform",
        options: [
          { name: "Create or Update", value: "upsert", description: "Create or update customer" },
          { name: "Delete", value: "delete", description: "Delete customer" },
        ],
        displayOptions: { show: { resource: ["customer"] } },
      },
      {
        name: "id",
        type: "string",
        required: true,
        default: "",
        description: "Customer ID",
        displayOptions: { show: { resource: ["customer"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields",
      },
    ],
    examples: [
      {
        name: "Create Customer",
        description: "Create or update a customer",
        parameters: {
          resource: "customer",
          operation: "upsert",
          id: "customer-123",
          additionalFields: { email: "customer@example.com" },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.customerio/",
  },

  "n8n-nodes-base.convertKit": {
    type: "n8n-nodes-base.convertKit",
    displayName: "ConvertKit",
    description: "Manage subscribers and forms in ConvertKit",
    category: "email",
    subcategory: "marketing",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "convertKitApi", required: true, description: "ConvertKit API secret" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "subscriber",
        description: "Resource to operate on",
        options: [
          { name: "Custom Field", value: "customField" },
          { name: "Form", value: "form" },
          { name: "Sequence", value: "sequence" },
          { name: "Subscriber", value: "subscriber" },
          { name: "Tag", value: "tag" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create subscriber" },
          { name: "Delete", value: "delete", description: "Delete subscriber" },
          { name: "Get", value: "get", description: "Get subscriber" },
          { name: "Get All", value: "getAll", description: "Get all subscribers" },
          { name: "Update", value: "update", description: "Update subscriber" },
        ],
        displayOptions: { show: { resource: ["subscriber"] } },
      },
      {
        name: "email",
        type: "string",
        required: true,
        default: "",
        description: "Subscriber email",
        displayOptions: { show: { resource: ["subscriber"] } },
      },
    ],
    examples: [
      {
        name: "Create Subscriber",
        description: "Add a new subscriber",
        parameters: {
          resource: "subscriber",
          operation: "create",
          email: "subscriber@example.com",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.convertkit/",
  },

  "n8n-nodes-base.drip": {
    type: "n8n-nodes-base.drip",
    displayName: "Drip",
    description: "Manage subscribers and campaigns in Drip",
    category: "email",
    subcategory: "marketing",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "dripApi", required: true, description: "Drip API token" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "subscriber",
        description: "Resource to operate on",
        options: [
          { name: "Campaign", value: "campaign" },
          { name: "Event", value: "event" },
          { name: "Subscriber", value: "subscriber" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create or Update", value: "create", description: "Create or update subscriber" },
          { name: "Delete", value: "delete", description: "Delete subscriber" },
          { name: "Get", value: "get", description: "Get subscriber" },
        ],
        displayOptions: { show: { resource: ["subscriber"] } },
      },
      {
        name: "email",
        type: "string",
        required: true,
        default: "",
        description: "Subscriber email",
        displayOptions: { show: { resource: ["subscriber"] } },
      },
    ],
    examples: [
      {
        name: "Add Subscriber",
        description: "Create or update a subscriber",
        parameters: {
          resource: "subscriber",
          operation: "create",
          email: "subscriber@example.com",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.drip/",
  },
};
