/**
 * Productivity Integration Nodes
 *
 * Google Sheets, Airtable, Coda, Google Calendar, etc.
 */

import type { NodeSchema } from "../types.js";

export const PRODUCTIVITY_NODES: Record<string, NodeSchema> = {
  "n8n-nodes-base.googleSheets": {
    type: "n8n-nodes-base.googleSheets",
    displayName: "Google Sheets",
    description: "Read, write, and manage data in Google Sheets",
    category: "productivity",
    typeVersion: 4,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "googleSheetsOAuth2Api", required: true, description: "Google OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "sheet",
        description: "Resource to operate on",
        options: [
          { name: "Document", value: "spreadsheet", description: "Manage spreadsheets" },
          { name: "Sheet Within Document", value: "sheet", description: "Manage sheets" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "appendOrUpdate",
        description: "Operation to perform",
        options: [
          { name: "Append or Update Row", value: "appendOrUpdate", description: "Append or update rows" },
          { name: "Append Row", value: "append", description: "Append rows" },
          { name: "Clear", value: "clear", description: "Clear a range" },
          { name: "Create", value: "create", description: "Create a sheet" },
          { name: "Delete", value: "delete", description: "Delete rows" },
          { name: "Read Rows", value: "read", description: "Read rows" },
          { name: "Update Row", value: "update", description: "Update rows" },
        ],
        displayOptions: { show: { resource: ["sheet"] } },
      },
      {
        name: "documentId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Spreadsheet ID or URL",
      },
      {
        name: "sheetName",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Sheet name",
        displayOptions: { show: { resource: ["sheet"] } },
      },
      {
        name: "columns",
        type: "resourceMapper",
        required: true,
        default: {},
        description: "Column mappings",
        displayOptions: { show: { resource: ["sheet"], operation: ["append", "appendOrUpdate", "update"] } },
      },
      {
        name: "filtersUI",
        type: "fixedCollection",
        required: false,
        default: {},
        description: "Filters for reading/updating",
        displayOptions: { show: { resource: ["sheet"], operation: ["read", "update", "delete", "appendOrUpdate"] } },
      },
      {
        name: "options",
        type: "collection",
        required: false,
        default: {},
        description: "Additional options",
      },
    ],
    examples: [
      {
        name: "Append Row",
        description: "Add a new row to a sheet",
        parameters: {
          resource: "sheet",
          operation: "append",
          documentId: "spreadsheet-id",
          sheetName: "Sheet1",
        },
      },
      {
        name: "Read All Rows",
        description: "Read all rows from a sheet",
        parameters: {
          resource: "sheet",
          operation: "read",
          documentId: "spreadsheet-id",
          sheetName: "Sheet1",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.googlesheets/",
  },

  "n8n-nodes-base.airtable": {
    type: "n8n-nodes-base.airtable",
    displayName: "Airtable",
    description: "Read, create, update, and delete records in Airtable",
    category: "productivity",
    typeVersion: 2,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "airtableTokenApi", required: false, description: "Airtable Personal Access Token" },
      { name: "airtableOAuth2Api", required: false, description: "Airtable OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "operation",
        type: "options",
        required: true,
        default: "search",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a record" },
          { name: "Delete", value: "delete", description: "Delete a record" },
          { name: "Get", value: "get", description: "Get a record" },
          { name: "Search", value: "search", description: "Search records" },
          { name: "Update", value: "update", description: "Update a record" },
          { name: "Upsert", value: "upsert", description: "Create or update a record" },
        ],
      },
      {
        name: "base",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Airtable base ID",
      },
      {
        name: "table",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Table name or ID",
      },
      {
        name: "id",
        type: "string",
        required: true,
        default: "",
        description: "Record ID",
        displayOptions: { show: { operation: ["get", "delete", "update"] } },
      },
      {
        name: "columns",
        type: "resourceMapper",
        required: true,
        default: {},
        description: "Field mappings",
        displayOptions: { show: { operation: ["create", "update", "upsert"] } },
      },
      {
        name: "options",
        type: "collection",
        required: false,
        default: {},
        description: "Additional options",
      },
    ],
    examples: [
      {
        name: "Create Record",
        description: "Create a new record in Airtable",
        parameters: {
          operation: "create",
          base: "app123",
          table: "Tasks",
        },
      },
      {
        name: "Search Records",
        description: "Search for records with a filter",
        parameters: {
          operation: "search",
          base: "app123",
          table: "Tasks",
          options: { filterByFormula: "{Status} = 'Done'" },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.airtable/",
  },

  "n8n-nodes-base.googleCalendar": {
    type: "n8n-nodes-base.googleCalendar",
    displayName: "Google Calendar",
    description: "Create, read, update, and delete calendar events",
    category: "productivity",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "googleCalendarOAuth2Api", required: true, description: "Google OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "event",
        description: "Resource to operate on",
        options: [
          { name: "Calendar", value: "calendar", description: "Manage calendars" },
          { name: "Event", value: "event", description: "Manage events" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create an event" },
          { name: "Delete", value: "delete", description: "Delete an event" },
          { name: "Get", value: "get", description: "Get an event" },
          { name: "Get All", value: "getAll", description: "Get all events" },
          { name: "Update", value: "update", description: "Update an event" },
        ],
        displayOptions: { show: { resource: ["event"] } },
      },
      {
        name: "calendar",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Calendar ID",
      },
      {
        name: "start",
        type: "string",
        required: true,
        default: "",
        description: "Event start time",
        displayOptions: { show: { resource: ["event"], operation: ["create"] } },
      },
      {
        name: "end",
        type: "string",
        required: true,
        default: "",
        description: "Event end time",
        displayOptions: { show: { resource: ["event"], operation: ["create"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields",
      },
    ],
    examples: [
      {
        name: "Create Event",
        description: "Create a calendar event",
        parameters: {
          resource: "event",
          operation: "create",
          calendar: "primary",
          start: "2024-01-15T10:00:00",
          end: "2024-01-15T11:00:00",
          additionalFields: { summary: "Meeting", description: "Team sync" },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.googlecalendar/",
  },

  "n8n-nodes-base.coda": {
    type: "n8n-nodes-base.coda",
    displayName: "Coda",
    description: "Manage tables and formulas in Coda documents",
    category: "productivity",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "codaApi", required: true, description: "Coda API token" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "row",
        description: "Resource to operate on",
        options: [
          { name: "Control", value: "control", description: "Get controls" },
          { name: "Formula", value: "formula", description: "Get formulas" },
          { name: "Row", value: "row", description: "Manage table rows" },
          { name: "Table", value: "table", description: "Get tables" },
          { name: "View", value: "view", description: "Get views" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "getAll",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a row" },
          { name: "Delete", value: "delete", description: "Delete a row" },
          { name: "Get", value: "get", description: "Get a row" },
          { name: "Get All", value: "getAll", description: "Get all rows" },
          { name: "Push Button", value: "pushButton", description: "Push a button" },
          { name: "Update", value: "update", description: "Update a row" },
        ],
        displayOptions: { show: { resource: ["row"] } },
      },
      {
        name: "docId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Document ID",
      },
      {
        name: "tableId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Table ID",
        displayOptions: { show: { resource: ["row"] } },
      },
    ],
    examples: [
      {
        name: "Get All Rows",
        description: "Get all rows from a table",
        parameters: {
          resource: "row",
          operation: "getAll",
          docId: "doc-id",
          tableId: "table-id",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.coda/",
  },

  "n8n-nodes-base.microsoftExcel": {
    type: "n8n-nodes-base.microsoftExcel",
    displayName: "Microsoft Excel 365",
    description: "Read and write data in Microsoft Excel Online",
    category: "productivity",
    typeVersion: 2,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "microsoftExcelOAuth2Api", required: true, description: "Microsoft OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "table",
        description: "Resource to operate on",
        options: [
          { name: "Table", value: "table", description: "Manage tables" },
          { name: "Workbook", value: "workbook", description: "Manage workbooks" },
          { name: "Worksheet", value: "worksheet", description: "Manage worksheets" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "getRows",
        description: "Operation to perform",
        options: [
          { name: "Add Row", value: "addRow", description: "Add a row" },
          { name: "Delete Row", value: "deleteRow", description: "Delete a row" },
          { name: "Get Columns", value: "getColumns", description: "Get columns" },
          { name: "Get Rows", value: "getRows", description: "Get rows" },
          { name: "Lookup", value: "lookup", description: "Lookup rows" },
          { name: "Update Row", value: "updateRow", description: "Update a row" },
        ],
        displayOptions: { show: { resource: ["table"] } },
      },
      {
        name: "workbook",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Workbook ID",
      },
      {
        name: "worksheet",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Worksheet name",
        displayOptions: { show: { resource: ["table", "worksheet"] } },
      },
      {
        name: "table",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Table name",
        displayOptions: { show: { resource: ["table"] } },
      },
    ],
    examples: [
      {
        name: "Get Rows",
        description: "Get all rows from a table",
        parameters: {
          resource: "table",
          operation: "getRows",
          workbook: "workbook-id",
          worksheet: "Sheet1",
          table: "Table1",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.microsoftexcel/",
  },

  "n8n-nodes-base.googleDocs": {
    type: "n8n-nodes-base.googleDocs",
    displayName: "Google Docs",
    description: "Create and edit Google Docs documents",
    category: "productivity",
    typeVersion: 2,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "googleDocsOAuth2Api", required: true, description: "Google OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a document" },
          { name: "Get", value: "get", description: "Get a document" },
          { name: "Update", value: "update", description: "Update a document" },
        ],
      },
      {
        name: "title",
        type: "string",
        required: true,
        default: "",
        description: "Document title",
        displayOptions: { show: { operation: ["create"] } },
      },
      {
        name: "documentId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Document ID",
        displayOptions: { show: { operation: ["get", "update"] } },
      },
      {
        name: "actionsUi",
        type: "fixedCollection",
        required: false,
        default: {},
        description: "Actions to perform",
        displayOptions: { show: { operation: ["update"] } },
      },
    ],
    examples: [
      {
        name: "Create Document",
        description: "Create a new Google Doc",
        parameters: {
          operation: "create",
          title: "New Document",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.googledocs/",
  },

  "n8n-nodes-base.googleSlides": {
    type: "n8n-nodes-base.googleSlides",
    displayName: "Google Slides",
    description: "Create and edit Google Slides presentations",
    category: "productivity",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "googleSlidesOAuth2Api", required: true, description: "Google OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "presentation",
        description: "Resource to operate on",
        options: [
          { name: "Page", value: "page", description: "Manage pages" },
          { name: "Presentation", value: "presentation", description: "Manage presentations" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a presentation" },
          { name: "Get", value: "get", description: "Get a presentation" },
          { name: "Get Slides", value: "getSlides", description: "Get slides" },
          { name: "Replace Text", value: "replaceText", description: "Replace text" },
        ],
        displayOptions: { show: { resource: ["presentation"] } },
      },
      {
        name: "title",
        type: "string",
        required: true,
        default: "",
        description: "Presentation title",
        displayOptions: { show: { resource: ["presentation"], operation: ["create"] } },
      },
      {
        name: "presentationId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Presentation ID",
        displayOptions: { show: { operation: ["get", "getSlides", "replaceText"] } },
      },
    ],
    examples: [
      {
        name: "Create Presentation",
        description: "Create a new presentation",
        parameters: {
          resource: "presentation",
          operation: "create",
          title: "My Presentation",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.googleslides/",
  },

  "n8n-nodes-base.googleForms": {
    type: "n8n-nodes-base.googleForms",
    displayName: "Google Forms",
    description: "Get form responses from Google Forms",
    category: "productivity",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "googleFormsOAuth2Api", required: true, description: "Google OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "operation",
        type: "options",
        required: true,
        default: "getResponses",
        description: "Operation to perform",
        options: [
          { name: "Get Responses", value: "getResponses", description: "Get form responses" },
        ],
      },
      {
        name: "formId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Form ID",
      },
    ],
    examples: [
      {
        name: "Get Responses",
        description: "Get all form responses",
        parameters: {
          operation: "getResponses",
          formId: "form-id",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.googleforms/",
  },

  "n8n-nodes-base.googleTasks": {
    type: "n8n-nodes-base.googleTasks",
    displayName: "Google Tasks",
    description: "Create, read, update, and delete tasks in Google Tasks",
    category: "productivity",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "googleTasksOAuth2Api", required: true, description: "Google OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "task",
        description: "Resource to operate on",
        options: [
          { name: "Task", value: "task", description: "Manage tasks" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a task" },
          { name: "Delete", value: "delete", description: "Delete a task" },
          { name: "Get", value: "get", description: "Get a task" },
          { name: "Get All", value: "getAll", description: "Get all tasks" },
          { name: "Update", value: "update", description: "Update a task" },
        ],
        displayOptions: { show: { resource: ["task"] } },
      },
      {
        name: "taskList",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Task list ID",
      },
      {
        name: "title",
        type: "string",
        required: true,
        default: "",
        description: "Task title",
        displayOptions: { show: { operation: ["create"] } },
      },
    ],
    examples: [
      {
        name: "Create Task",
        description: "Create a new task",
        parameters: {
          resource: "task",
          operation: "create",
          taskList: "tasklist-id",
          title: "New Task",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.googletasks/",
  },

  "n8n-nodes-base.googleContacts": {
    type: "n8n-nodes-base.googleContacts",
    displayName: "Google Contacts",
    description: "Manage contacts in Google Contacts",
    category: "productivity",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "googleContactsOAuth2Api", required: true, description: "Google OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "contact",
        description: "Resource to operate on",
        options: [
          { name: "Contact", value: "contact", description: "Manage contacts" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a contact" },
          { name: "Delete", value: "delete", description: "Delete a contact" },
          { name: "Get", value: "get", description: "Get a contact" },
          { name: "Get All", value: "getAll", description: "Get all contacts" },
          { name: "Update", value: "update", description: "Update a contact" },
        ],
        displayOptions: { show: { resource: ["contact"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields",
      },
    ],
    examples: [
      {
        name: "Create Contact",
        description: "Create a new contact",
        parameters: {
          resource: "contact",
          operation: "create",
          additionalFields: { familyName: "Doe", givenName: "John" },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.googlecontacts/",
  },

  "n8n-nodes-base.calendly": {
    type: "n8n-nodes-base.calendly",
    displayName: "Calendly",
    description: "Manage events and invitees in Calendly",
    category: "productivity",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "calendlyApi", required: true, description: "Calendly API token" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "event",
        description: "Resource to operate on",
        options: [
          { name: "Event", value: "event", description: "Get events" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "getAll",
        description: "Operation to perform",
        options: [
          { name: "Get All", value: "getAll", description: "Get all events" },
        ],
        displayOptions: { show: { resource: ["event"] } },
      },
      {
        name: "returnAll",
        type: "boolean",
        required: true,
        default: false,
        description: "Return all results",
      },
    ],
    examples: [
      {
        name: "Get Events",
        description: "Get all scheduled events",
        parameters: {
          resource: "event",
          operation: "getAll",
          returnAll: true,
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.calendly/",
  },

  "n8n-nodes-base.clockify": {
    type: "n8n-nodes-base.clockify",
    displayName: "Clockify",
    description: "Track time and manage projects in Clockify",
    category: "productivity",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "clockifyApi", required: true, description: "Clockify API key" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "timeEntry",
        description: "Resource to operate on",
        options: [
          { name: "Client", value: "client" },
          { name: "Project", value: "project" },
          { name: "Tag", value: "tag" },
          { name: "Task", value: "task" },
          { name: "Time Entry", value: "timeEntry" },
          { name: "User", value: "user" },
          { name: "Workspace", value: "workspace" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a time entry" },
          { name: "Delete", value: "delete", description: "Delete a time entry" },
          { name: "Get", value: "get", description: "Get a time entry" },
          { name: "Update", value: "update", description: "Update a time entry" },
        ],
        displayOptions: { show: { resource: ["timeEntry"] } },
      },
      {
        name: "workspaceId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Workspace ID",
      },
    ],
    examples: [
      {
        name: "Create Time Entry",
        description: "Log a time entry",
        parameters: {
          resource: "timeEntry",
          operation: "create",
          workspaceId: "workspace-id",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.clockify/",
  },

  "n8n-nodes-base.toggl": {
    type: "n8n-nodes-base.toggl",
    displayName: "Toggl Track",
    description: "Track time in Toggl",
    category: "productivity",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "togglApi", required: true, description: "Toggl API token" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "timeEntry",
        description: "Resource to operate on",
        options: [
          { name: "Time Entry", value: "timeEntry" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a time entry" },
          { name: "Delete", value: "delete", description: "Delete a time entry" },
          { name: "Get", value: "get", description: "Get a time entry" },
          { name: "Get All", value: "getAll", description: "Get all time entries" },
          { name: "Start", value: "start", description: "Start a time entry" },
          { name: "Stop", value: "stop", description: "Stop a time entry" },
          { name: "Update", value: "update", description: "Update a time entry" },
        ],
        displayOptions: { show: { resource: ["timeEntry"] } },
      },
      {
        name: "workspaceId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Workspace ID",
      },
    ],
    examples: [
      {
        name: "Start Timer",
        description: "Start a time entry",
        parameters: {
          resource: "timeEntry",
          operation: "start",
          workspaceId: "workspace-id",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.toggl/",
  },

  "n8n-nodes-base.harvest": {
    type: "n8n-nodes-base.harvest",
    displayName: "Harvest",
    description: "Track time and manage invoices in Harvest",
    category: "productivity",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "harvestApi", required: true, description: "Harvest API credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "timeEntry",
        description: "Resource to operate on",
        options: [
          { name: "Client", value: "client" },
          { name: "Company", value: "company" },
          { name: "Contact", value: "contact" },
          { name: "Estimate", value: "estimate" },
          { name: "Expense", value: "expense" },
          { name: "Invoice", value: "invoice" },
          { name: "Project", value: "project" },
          { name: "Task", value: "task" },
          { name: "Time Entry", value: "timeEntry" },
          { name: "User", value: "user" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a time entry" },
          { name: "Delete", value: "delete", description: "Delete a time entry" },
          { name: "Get", value: "get", description: "Get a time entry" },
          { name: "Get All", value: "getAll", description: "Get all time entries" },
          { name: "Update", value: "update", description: "Update a time entry" },
        ],
        displayOptions: { show: { resource: ["timeEntry"] } },
      },
    ],
    examples: [
      {
        name: "Create Time Entry",
        description: "Log time to a project",
        parameters: {
          resource: "timeEntry",
          operation: "create",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.harvest/",
  },

  "n8n-nodes-base.dropcontact": {
    type: "n8n-nodes-base.dropcontact",
    displayName: "Dropcontact",
    description: "Enrich and verify contact data",
    category: "productivity",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "dropcontactApi", required: true, description: "Dropcontact API key" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "contact",
        description: "Resource to operate on",
        options: [
          { name: "Contact", value: "contact" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "enrich",
        description: "Operation to perform",
        options: [
          { name: "Enrich", value: "enrich", description: "Enrich contact data" },
          { name: "Fetch Request", value: "fetchRequest", description: "Fetch enrichment request" },
        ],
        displayOptions: { show: { resource: ["contact"] } },
      },
      {
        name: "email",
        type: "string",
        required: false,
        default: "",
        description: "Contact email",
        displayOptions: { show: { operation: ["enrich"] } },
      },
    ],
    examples: [
      {
        name: "Enrich Contact",
        description: "Enrich a contact with additional data",
        parameters: {
          resource: "contact",
          operation: "enrich",
          email: "contact@example.com",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.dropcontact/",
  },
};
