/**
 * Project Management Integration Nodes
 *
 * Jira, Asana, ClickUp, Trello, Monday.com, Linear, Notion, etc.
 */

import type { NodeSchema } from "../types.js";

export const PROJECT_MANAGEMENT_NODES: Record<string, NodeSchema> = {
  "n8n-nodes-base.jira": {
    type: "n8n-nodes-base.jira",
    displayName: "Jira Software",
    description: "Manage issues, projects, and users in Jira",
    category: "project",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "jiraSoftwareCloudApi", required: false, description: "Jira Cloud API credentials" },
      { name: "jiraSoftwareServerApi", required: false, description: "Jira Server API credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "issue",
        description: "Resource to operate on",
        options: [
          { name: "Issue", value: "issue", description: "Manage issues" },
          { name: "Issue Comment", value: "issueComment", description: "Manage issue comments" },
          { name: "Issue Attachment", value: "issueAttachment", description: "Manage attachments" },
          { name: "User", value: "user", description: "Manage users" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Changelog", value: "changelog", description: "Get issue changelog" },
          { name: "Create", value: "create", description: "Create an issue" },
          { name: "Delete", value: "delete", description: "Delete an issue" },
          { name: "Get", value: "get", description: "Get an issue" },
          { name: "Notify", value: "notify", description: "Send notification" },
          { name: "Status", value: "status", description: "Get statuses" },
          { name: "Transition", value: "transition", description: "Transition issue" },
          { name: "Update", value: "update", description: "Update an issue" },
        ],
        displayOptions: { show: { resource: ["issue"] } },
      },
      {
        name: "project",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Project key or ID",
        displayOptions: { show: { resource: ["issue"], operation: ["create"] } },
      },
      {
        name: "issueType",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Issue type",
        displayOptions: { show: { resource: ["issue"], operation: ["create"] } },
      },
      {
        name: "summary",
        type: "string",
        required: true,
        default: "",
        description: "Issue summary/title",
        displayOptions: { show: { resource: ["issue"], operation: ["create"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields",
        options: [
          { name: "assignee", value: "assignee", description: "Assignee" },
          { name: "description", value: "description", description: "Description" },
          { name: "labels", value: "labels", description: "Labels" },
          { name: "priority", value: "priority", description: "Priority" },
          { name: "reporter", value: "reporter", description: "Reporter" },
        ],
      },
    ],
    examples: [
      {
        name: "Create Issue",
        description: "Create a new Jira issue",
        parameters: {
          resource: "issue",
          operation: "create",
          project: "PROJECT-KEY",
          issueType: "Task",
          summary: "New task from n8n",
          additionalFields: { description: "Task description", priority: "Medium" },
        },
      },
      {
        name: "Transition Issue",
        description: "Move issue to different status",
        parameters: {
          resource: "issue",
          operation: "transition",
          issueKey: "PROJECT-123",
          transitionTo: "Done",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.jira/",
  },

  "n8n-nodes-base.asana": {
    type: "n8n-nodes-base.asana",
    displayName: "Asana",
    description: "Manage tasks, projects, and workspaces in Asana",
    category: "project",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "asanaApi", required: false, description: "Asana Personal Access Token" },
      { name: "asanaOAuth2Api", required: false, description: "Asana OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "task",
        description: "Resource to operate on",
        options: [
          { name: "Project", value: "project", description: "Manage projects" },
          { name: "Subtask", value: "subtask", description: "Manage subtasks" },
          { name: "Task", value: "task", description: "Manage tasks" },
          { name: "Task Comment", value: "taskComment", description: "Manage task comments" },
          { name: "Task Tag", value: "taskTag", description: "Manage task tags" },
          { name: "User", value: "user", description: "Get user information" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a task" },
          { name: "Delete", value: "delete", description: "Delete a task" },
          { name: "Get", value: "get", description: "Get a task" },
          { name: "Get All", value: "getAll", description: "Get all tasks" },
          { name: "Move", value: "move", description: "Move a task" },
          { name: "Search", value: "search", description: "Search tasks" },
          { name: "Update", value: "update", description: "Update a task" },
        ],
        displayOptions: { show: { resource: ["task"] } },
      },
      {
        name: "workspace",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Workspace ID",
        displayOptions: { show: { resource: ["task"], operation: ["create"] } },
      },
      {
        name: "name",
        type: "string",
        required: true,
        default: "",
        description: "Task name",
        displayOptions: { show: { resource: ["task"], operation: ["create"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields",
        options: [
          { name: "assignee", value: "assignee", description: "Assignee" },
          { name: "due_on", value: "due_on", description: "Due date" },
          { name: "notes", value: "notes", description: "Task notes" },
          { name: "projects", value: "projects", description: "Projects" },
        ],
      },
    ],
    examples: [
      {
        name: "Create Task",
        description: "Create a new task in Asana",
        parameters: {
          resource: "task",
          operation: "create",
          workspace: "workspace-id",
          name: "New task from n8n",
          additionalFields: { notes: "Task description" },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.asana/",
  },

  "n8n-nodes-base.clickUp": {
    type: "n8n-nodes-base.clickUp",
    displayName: "ClickUp",
    description: "Manage tasks, lists, and folders in ClickUp",
    category: "project",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "clickUpApi", required: false, description: "ClickUp Personal Token" },
      { name: "clickUpOAuth2Api", required: false, description: "ClickUp OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "task",
        description: "Resource to operate on",
        options: [
          { name: "Checklist", value: "checklist" },
          { name: "Checklist Item", value: "checklistItem" },
          { name: "Comment", value: "comment" },
          { name: "Folder", value: "folder" },
          { name: "Goal", value: "goal" },
          { name: "Goal Key Result", value: "goalKeyResult" },
          { name: "Guest", value: "guest" },
          { name: "List", value: "list" },
          { name: "Space Tag", value: "spaceTag" },
          { name: "Task", value: "task" },
          { name: "Task Dependency", value: "taskDependency" },
          { name: "Task List", value: "taskList" },
          { name: "Task Tag", value: "taskTag" },
          { name: "Time Entry", value: "timeEntry" },
          { name: "Time Entry Tag", value: "timeEntryTag" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a task" },
          { name: "Delete", value: "delete", description: "Delete a task" },
          { name: "Get", value: "get", description: "Get a task" },
          { name: "Get All", value: "getAll", description: "Get all tasks" },
          { name: "Set Custom Field", value: "setCustomField", description: "Set custom field" },
          { name: "Update", value: "update", description: "Update a task" },
        ],
        displayOptions: { show: { resource: ["task"] } },
      },
      {
        name: "list",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "List ID to create the task in",
        displayOptions: { show: { resource: ["task"], operation: ["create"] } },
      },
      {
        name: "name",
        type: "string",
        required: true,
        default: "",
        description: "Task name",
        displayOptions: { show: { resource: ["task"], operation: ["create"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields",
      },
    ],
    examples: [
      {
        name: "Create Task",
        description: "Create a new task in ClickUp",
        parameters: {
          resource: "task",
          operation: "create",
          list: "list-id",
          name: "New task from n8n",
          additionalFields: { description: "Task description" },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.clickup/",
  },

  "n8n-nodes-base.trello": {
    type: "n8n-nodes-base.trello",
    displayName: "Trello",
    description: "Manage boards, lists, and cards in Trello",
    category: "project",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "trelloApi", required: true, description: "Trello API credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "card",
        description: "Resource to operate on",
        options: [
          { name: "Attachment", value: "attachment" },
          { name: "Board", value: "board" },
          { name: "Card", value: "card" },
          { name: "Card Comment", value: "cardComment" },
          { name: "Checklist", value: "checklist" },
          { name: "Label", value: "label" },
          { name: "List", value: "list" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a card" },
          { name: "Delete", value: "delete", description: "Delete a card" },
          { name: "Get", value: "get", description: "Get a card" },
          { name: "Update", value: "update", description: "Update a card" },
        ],
        displayOptions: { show: { resource: ["card"] } },
      },
      {
        name: "listId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "List ID to create the card in",
        displayOptions: { show: { resource: ["card"], operation: ["create"] } },
      },
      {
        name: "name",
        type: "string",
        required: true,
        default: "",
        description: "Card name",
        displayOptions: { show: { resource: ["card"], operation: ["create"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields",
      },
    ],
    examples: [
      {
        name: "Create Card",
        description: "Create a new card in Trello",
        parameters: {
          resource: "card",
          operation: "create",
          listId: "list-id",
          name: "New card from n8n",
          additionalFields: { desc: "Card description" },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.trello/",
  },

  "n8n-nodes-base.mondayCom": {
    type: "n8n-nodes-base.mondayCom",
    displayName: "Monday.com",
    description: "Manage boards, groups, and items in Monday.com",
    category: "project",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "mondayComApi", required: true, description: "Monday.com API token" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "boardItem",
        description: "Resource to operate on",
        options: [
          { name: "Board", value: "board" },
          { name: "Board Column", value: "boardColumn" },
          { name: "Board Group", value: "boardGroup" },
          { name: "Board Item", value: "boardItem" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Add Update", value: "addUpdate", description: "Add an update" },
          { name: "Archive", value: "archive", description: "Archive an item" },
          { name: "Change Column Value", value: "changeColumnValue", description: "Change column value" },
          { name: "Change Multiple Column Values", value: "changeMultipleColumnValues", description: "Change multiple values" },
          { name: "Create", value: "create", description: "Create an item" },
          { name: "Delete", value: "delete", description: "Delete an item" },
          { name: "Get", value: "get", description: "Get an item" },
          { name: "Get All", value: "getAll", description: "Get all items" },
          { name: "Get By Column Value", value: "getByColumnValue", description: "Get by column value" },
          { name: "Move", value: "move", description: "Move an item" },
        ],
        displayOptions: { show: { resource: ["boardItem"] } },
      },
      {
        name: "boardId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Board ID",
        displayOptions: { show: { resource: ["boardItem"] } },
      },
      {
        name: "groupId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Group ID",
        displayOptions: { show: { resource: ["boardItem"], operation: ["create"] } },
      },
      {
        name: "name",
        type: "string",
        required: true,
        default: "",
        description: "Item name",
        displayOptions: { show: { resource: ["boardItem"], operation: ["create"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields",
      },
    ],
    examples: [
      {
        name: "Create Item",
        description: "Create a new item in Monday.com",
        parameters: {
          resource: "boardItem",
          operation: "create",
          boardId: "board-id",
          groupId: "group-id",
          name: "New item from n8n",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.mondaycom/",
  },

  "n8n-nodes-base.linear": {
    type: "n8n-nodes-base.linear",
    displayName: "Linear",
    description: "Manage issues, projects, and teams in Linear",
    category: "project",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "linearApi", required: false, description: "Linear API key" },
      { name: "linearOAuth2Api", required: false, description: "Linear OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "issue",
        description: "Resource to operate on",
        options: [
          { name: "Issue", value: "issue", description: "Manage issues" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create an issue" },
          { name: "Delete", value: "delete", description: "Delete an issue" },
          { name: "Get", value: "get", description: "Get an issue" },
          { name: "Get All", value: "getAll", description: "Get all issues" },
          { name: "Update", value: "update", description: "Update an issue" },
        ],
        displayOptions: { show: { resource: ["issue"] } },
      },
      {
        name: "teamId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Team ID",
        displayOptions: { show: { resource: ["issue"], operation: ["create"] } },
      },
      {
        name: "title",
        type: "string",
        required: true,
        default: "",
        description: "Issue title",
        displayOptions: { show: { resource: ["issue"], operation: ["create"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields",
      },
    ],
    examples: [
      {
        name: "Create Issue",
        description: "Create a new issue in Linear",
        parameters: {
          resource: "issue",
          operation: "create",
          teamId: "team-id",
          title: "New issue from n8n",
          additionalFields: { description: "Issue description" },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.linear/",
  },

  "n8n-nodes-base.notion": {
    type: "n8n-nodes-base.notion",
    displayName: "Notion",
    description: "Manage databases, pages, and blocks in Notion",
    category: "project",
    subcategory: "productivity",
    typeVersion: 2,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "notionApi", required: false, description: "Notion Integration Token" },
      { name: "notionOAuth2Api", required: false, description: "Notion OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "databasePage",
        description: "Resource to operate on",
        options: [
          { name: "Block", value: "block", description: "Manage blocks" },
          { name: "Database", value: "database", description: "Manage databases" },
          { name: "Database Page", value: "databasePage", description: "Manage database pages" },
          { name: "Page", value: "page", description: "Manage pages" },
          { name: "User", value: "user", description: "Get user information" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a database page" },
          { name: "Get", value: "get", description: "Get a database page" },
          { name: "Get All", value: "getAll", description: "Get all database pages" },
          { name: "Update", value: "update", description: "Update a database page" },
        ],
        displayOptions: { show: { resource: ["databasePage"] } },
      },
      {
        name: "databaseId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Database ID",
        displayOptions: { show: { resource: ["databasePage"], operation: ["create", "getAll"] } },
      },
      {
        name: "propertiesUi",
        type: "fixedCollection",
        required: false,
        default: {},
        description: "Page properties",
        displayOptions: { show: { resource: ["databasePage"], operation: ["create", "update"] } },
      },
    ],
    examples: [
      {
        name: "Create Database Page",
        description: "Create a new page in a Notion database",
        parameters: {
          resource: "databasePage",
          operation: "create",
          databaseId: "database-id",
          propertiesUi: { propertyValues: [{ key: "Name", title: "New page from n8n" }] },
        },
      },
      {
        name: "Query Database",
        description: "Get all pages from a database",
        parameters: {
          resource: "databasePage",
          operation: "getAll",
          databaseId: "database-id",
          returnAll: true,
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.notion/",
  },

  "n8n-nodes-base.todoist": {
    type: "n8n-nodes-base.todoist",
    displayName: "Todoist",
    description: "Manage tasks and projects in Todoist",
    category: "project",
    subcategory: "productivity",
    typeVersion: 2,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "todoistApi", required: false, description: "Todoist API token" },
      { name: "todoistOAuth2Api", required: false, description: "Todoist OAuth2 credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "task",
        description: "Resource to operate on",
        options: [
          { name: "Task", value: "task", description: "Manage tasks" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Close", value: "close", description: "Close a task" },
          { name: "Create", value: "create", description: "Create a task" },
          { name: "Delete", value: "delete", description: "Delete a task" },
          { name: "Get", value: "get", description: "Get a task" },
          { name: "Get All", value: "getAll", description: "Get all tasks" },
          { name: "Move", value: "move", description: "Move a task" },
          { name: "Reopen", value: "reopen", description: "Reopen a task" },
          { name: "Sync", value: "sync", description: "Sync tasks" },
          { name: "Update", value: "update", description: "Update a task" },
        ],
        displayOptions: { show: { resource: ["task"] } },
      },
      {
        name: "content",
        type: "string",
        required: true,
        default: "",
        description: "Task content/title",
        displayOptions: { show: { resource: ["task"], operation: ["create"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields",
      },
    ],
    examples: [
      {
        name: "Create Task",
        description: "Create a new task in Todoist",
        parameters: {
          resource: "task",
          operation: "create",
          content: "New task from n8n",
          additionalFields: { projectId: "project-id" },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.todoist/",
  },

  "n8n-nodes-base.baserow": {
    type: "n8n-nodes-base.baserow",
    displayName: "Baserow",
    description: "Manage rows in Baserow databases",
    category: "project",
    subcategory: "database",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "baserowApi", required: true, description: "Baserow API token" },
    ],
    parameters: [
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a row" },
          { name: "Delete", value: "delete", description: "Delete a row" },
          { name: "Get", value: "get", description: "Get a row" },
          { name: "Get All", value: "getAll", description: "Get all rows" },
          { name: "Update", value: "update", description: "Update a row" },
        ],
      },
      {
        name: "databaseId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Database ID",
      },
      {
        name: "tableId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Table ID",
      },
      {
        name: "fieldsUi",
        type: "fixedCollection",
        required: false,
        default: {},
        description: "Field values",
        displayOptions: { show: { operation: ["create", "update"] } },
      },
    ],
    examples: [
      {
        name: "Create Row",
        description: "Create a new row in Baserow",
        parameters: {
          operation: "create",
          databaseId: "database-id",
          tableId: "table-id",
          fieldsUi: { fieldValues: [{ fieldName: "Name", fieldValue: "New row" }] },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.baserow/",
  },

  "n8n-nodes-base.seaTable": {
    type: "n8n-nodes-base.seaTable",
    displayName: "SeaTable",
    description: "Manage rows in SeaTable databases",
    category: "project",
    subcategory: "database",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "seaTableApi", required: true, description: "SeaTable API token" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "row",
        description: "Resource to operate on",
        options: [
          { name: "Row", value: "row", description: "Manage rows" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a row" },
          { name: "Delete", value: "delete", description: "Delete a row" },
          { name: "Get", value: "get", description: "Get a row" },
          { name: "Get All", value: "getAll", description: "Get all rows" },
          { name: "Update", value: "update", description: "Update a row" },
        ],
        displayOptions: { show: { resource: ["row"] } },
      },
      {
        name: "tableName",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Table name",
      },
      {
        name: "columnsUi",
        type: "fixedCollection",
        required: false,
        default: {},
        description: "Column values",
        displayOptions: { show: { operation: ["create", "update"] } },
      },
    ],
    examples: [
      {
        name: "Create Row",
        description: "Create a new row in SeaTable",
        parameters: {
          resource: "row",
          operation: "create",
          tableName: "Table1",
          columnsUi: { columnValues: [{ columnName: "Name", columnValue: "New row" }] },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.seatable/",
  },

  "n8n-nodes-base.wrike": {
    type: "n8n-nodes-base.wrike",
    displayName: "Wrike",
    description: "Manage tasks and folders in Wrike",
    category: "project",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "wrikeApi", required: true, description: "Wrike API token" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "task",
        description: "Resource to operate on",
        options: [
          { name: "Folder", value: "folder" },
          { name: "Task", value: "task" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a task" },
          { name: "Delete", value: "delete", description: "Delete a task" },
          { name: "Get", value: "get", description: "Get a task" },
          { name: "Get All", value: "getAll", description: "Get all tasks" },
          { name: "Update", value: "update", description: "Update a task" },
        ],
        displayOptions: { show: { resource: ["task"] } },
      },
      {
        name: "folderId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Folder ID",
        displayOptions: { show: { resource: ["task"], operation: ["create"] } },
      },
      {
        name: "title",
        type: "string",
        required: true,
        default: "",
        description: "Task title",
        displayOptions: { show: { resource: ["task"], operation: ["create"] } },
      },
      {
        name: "additionalFields",
        type: "collection",
        required: false,
        default: {},
        description: "Additional fields",
      },
    ],
    examples: [
      {
        name: "Create Task",
        description: "Create a new task in Wrike",
        parameters: {
          resource: "task",
          operation: "create",
          folderId: "folder-id",
          title: "New task from n8n",
          additionalFields: { description: "Task description" },
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.wrike/",
  },

  "n8n-nodes-base.teamwork": {
    type: "n8n-nodes-base.teamwork",
    displayName: "Teamwork",
    description: "Manage tasks and projects in Teamwork",
    category: "project",
    typeVersion: 1,
    inputs: ["main"],
    outputs: ["main"],
    credentials: [
      { name: "teamworkApi", required: true, description: "Teamwork API credentials" },
    ],
    parameters: [
      {
        name: "resource",
        type: "options",
        required: true,
        default: "task",
        description: "Resource to operate on",
        options: [
          { name: "Task", value: "task" },
        ],
      },
      {
        name: "operation",
        type: "options",
        required: true,
        default: "create",
        description: "Operation to perform",
        options: [
          { name: "Create", value: "create", description: "Create a task" },
          { name: "Delete", value: "delete", description: "Delete a task" },
          { name: "Get", value: "get", description: "Get a task" },
          { name: "Get All", value: "getAll", description: "Get all tasks" },
          { name: "Update", value: "update", description: "Update a task" },
        ],
        displayOptions: { show: { resource: ["task"] } },
      },
      {
        name: "tasklistId",
        type: "resourceLocator",
        required: true,
        default: "",
        description: "Task list ID",
        displayOptions: { show: { resource: ["task"], operation: ["create"] } },
      },
      {
        name: "content",
        type: "string",
        required: true,
        default: "",
        description: "Task content",
        displayOptions: { show: { resource: ["task"], operation: ["create"] } },
      },
    ],
    examples: [
      {
        name: "Create Task",
        description: "Create a new task in Teamwork",
        parameters: {
          resource: "task",
          operation: "create",
          tasklistId: "tasklist-id",
          content: "New task from n8n",
        },
      },
    ],
    documentationUrl: "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.teamwork/",
  },
};
